#ifndef RUSH_SEAMAPISLANDICON_H
#define RUSH_SEAMAPISLANDICON_H

#include <seaMap/seaMapEventManager.h>
#include <seaMap/seaMapEventTrigger.h>

// --------------------
// ENUMS
// --------------------

enum SeaMapIslandDrawIcon_Unknown
{
    CH_ISLANDDRAWICON_UNKNOWN_0,
    CH_ISLANDDRAWICON_UNKNOWN_Z1,
    CH_ISLANDDRAWICON_UNKNOWN_Z2,
    CH_ISLANDDRAWICON_UNKNOWN_Z3,
    CH_ISLANDDRAWICON_UNKNOWN_Z4,
    CH_ISLANDDRAWICON_UNKNOWN_Z5,
    CH_ISLANDDRAWICON_UNKNOWN_Z6,
    CH_ISLANDDRAWICON_UNKNOWN_Z7,
    CH_ISLANDDRAWICON_UNKNOWN_ZFINAL,
    CH_ISLANDDRAWICON_UNKNOWN_SOUTHERN_ISLAND,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_1,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_2,
    CH_ISLANDDRAWICON_UNKNOWN_DAIKUN_ISLAND,
    CH_ISLANDDRAWICON_UNKNOWN_13,
    CH_ISLANDDRAWICON_UNKNOWN_KYLOK_ISLAND,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_3,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_4,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_5,
    CH_ISLANDDRAWICON_UNKNOWN_18,
    CH_ISLANDDRAWICON_UNKNOWN_19,
    CH_ISLANDDRAWICON_UNKNOWN_20,
    CH_ISLANDDRAWICON_UNKNOWN_21,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_6,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_7,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_8,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_9,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_10,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_11,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_12,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_13,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_14,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_15,
    CH_ISLANDDRAWICON_UNKNOWN_HIDDEN_ISLAND_16,
    CH_ISLANDDRAWICON_UNKNOWN_33,
    CH_ISLANDDRAWICON_UNKNOWN_34,
    CH_ISLANDDRAWICON_UNKNOWN_35,
    CH_ISLANDDRAWICON_UNKNOWN_36,
    CH_ISLANDDRAWICON_UNKNOWN_37,
    CH_ISLANDDRAWICON_UNKNOWN_38,
    CH_ISLANDDRAWICON_UNKNOWN_39,
    CH_ISLANDDRAWICON_UNKNOWN_ISLAND_ZFINAL,
    CH_ISLANDDRAWICON_UNKNOWN_41,
};

// --------------------
// STRUCTS
// --------------------

typedef struct SeaMapIslandIcon_
{
    SeaMapObject objWork;
    s32 field_10;
    SeaMapEventListener *objectUnknown;
} SeaMapIslandIcon;

// --------------------
// FUNCTIONS
// --------------------

NOT_DECOMPILED SeaMapObject *SeaMapIslandIcon__Create(const CHEVObjectType *objectType, CHEVObject *mapObject);
NOT_DECOMPILED void SeaMapIslandIcon__Destructor2(Task *task);
NOT_DECOMPILED void SeaMapIslandIcon__Main1(void);
NOT_DECOMPILED void SeaMapIslandIcon__Main2(void);
NOT_DECOMPILED void SeaMapIslandIcon__Destructor1(Task *task);
NOT_DECOMPILED void SeaMapIslandIcon__Func_2048824(CHEVObject *mapObject);
NOT_DECOMPILED BOOL SeaMapIslandIcon__ViewCheck(CHEVObject *mapObject, fx32 x, fx32 y, BOOL flag);

#endif // RUSH_SEAMAPISLANDICON_H