#include <stage/player/player.h>

// --------------------
// ENUMS
// --------------------

enum PlayerModelIndex
{
    PLAYERMODEL_PLAYER,
    PLAYERMODEL_BALL,
    PLAYERMODEL_TAIL,
};

enum PlayerModelAnimationID
{
    // Common Animations
    PLAYER_MODELANI_com_brake1_01,
    PLAYER_MODELANI_com_brake1_02,
    PLAYER_MODELANI_com_brake1_03,
    PLAYER_MODELANI_com_brake2_01,
    PLAYER_MODELANI_com_brake2_02,
    PLAYER_MODELANI_com_brake2_03,
    PLAYER_MODELANI_com_die_01,
    PLAYER_MODELANI_com_die_02,
    PLAYER_MODELANI_com_dmg_b,
    PLAYER_MODELANI_com_dmg_f,
    PLAYER_MODELANI_com_graind,
    PLAYER_MODELANI_com_jump_03,
    PLAYER_MODELANI_com_jump_d,
    PLAYER_MODELANI_com_jump_f_01,
    PLAYER_MODELANI_com_jump_s_01,
    PLAYER_MODELANI_com_jump_s_02,
    PLAYER_MODELANI_com_jump_s_03,
    PLAYER_MODELANI_com_squat,
    PLAYER_MODELANI_com_st_b_01,
    PLAYER_MODELANI_com_st_b_02,
    PLAYER_MODELANI_com_st_f_01,
    PLAYER_MODELANI_com_st_f_02,
    PLAYER_MODELANI_com_tk_051,
    PLAYER_MODELANI_com_tk_061,
    PLAYER_MODELANI_com_tk_071,
    PLAYER_MODELANI_com_tk_081_01,
    PLAYER_MODELANI_com_tk_081_02,
    PLAYER_MODELANI_com_tk_081_03,
    PLAYER_MODELANI_com_turn01,
    PLAYER_MODELANI_com_up_01,
    PLAYER_MODELANI_com_up_02,
    PLAYER_MODELANI_com_wall_01,
    PLAYER_MODELANI_com_wall_02,
    PLAYER_MODELANI_com_hang_rot,
    PLAYER_MODELANI_com_jump_m_01,
    PLAYER_MODELANI_com_rope_tar,
    PLAYER_MODELANI_com_fan,
    PLAYER_MODELANI_com_wing,
    PLAYER_MODELANI_com_piston_01,
    PLAYER_MODELANI_com_piston_02,
    PLAYER_MODELANI_com_dive_std,
    PLAYER_MODELANI_com_icicle,
    PLAYER_MODELANI_com_anchor,
    PLAYER_MODELANI_com_crane,
    PLAYER_MODELANI_com_iceland,
    PLAYER_MODELANI_com_trmpln,
    PLAYER_MODELANI_com_wg_gun_00,
    PLAYER_MODELANI_com_wg_gun_01,

    // Sonic's Animations
    PLAYER_MODELANI_son_fw,
    PLAYER_MODELANI_son_goal,
    PLAYER_MODELANI_son_goal1,
    PLAYER_MODELANI_son_goal2,
    PLAYER_MODELANI_son_screw,
    PLAYER_MODELANI_son_tk_001_01,
    PLAYER_MODELANI_son_tk_001_02,
    PLAYER_MODELANI_son_tk_001_03,
    PLAYER_MODELANI_son_tk_001_04,
    PLAYER_MODELANI_son_tk_011_01,
    PLAYER_MODELANI_son_tk_011_02,
    PLAYER_MODELANI_son_tk_011_03,
    PLAYER_MODELANI_son_tk_021,
    PLAYER_MODELANI_son_tk_031,
    PLAYER_MODELANI_son_tk_041,
    PLAYER_MODELANI_son_touch1,
    PLAYER_MODELANI_son_walk1,
    PLAYER_MODELANI_son_walk2,
    PLAYER_MODELANI_son_walk3,
    PLAYER_MODELANI_son_walk4,
    PLAYER_MODELANI_son_walk5,
    PLAYER_MODELANI_son_walk6,
    PLAYER_MODELANI_son_start_01,
    PLAYER_MODELANI_son_start_02,
    PLAYER_MODELANI_son_start_03,

    // Blazes's Animations
    PLAYER_MODELANI_blz_ball,
    PLAYER_MODELANI_blz_dush1,
    PLAYER_MODELANI_blz_dush2,
    PLAYER_MODELANI_blz_fw,
    PLAYER_MODELANI_blz_goal,
    PLAYER_MODELANI_blz_goal1,
    PLAYER_MODELANI_blz_goal2,
    PLAYER_MODELANI_blz_hover,
    PLAYER_MODELANI_blz_tk_001_01,
    PLAYER_MODELANI_blz_tk_001_02,
    PLAYER_MODELANI_blz_tk_001_03,
    PLAYER_MODELANI_blz_tk_001_04,
    PLAYER_MODELANI_blz_tk_011_01,
    PLAYER_MODELANI_blz_tk_011_02,
    PLAYER_MODELANI_blz_tk_021,
    PLAYER_MODELANI_blz_tk_031,
    PLAYER_MODELANI_blz_tk_041,
    PLAYER_MODELANI_blz_touch1_01,
    PLAYER_MODELANI_blz_walk1,
    PLAYER_MODELANI_blz_walk2,
    PLAYER_MODELANI_blz_walk3,
    PLAYER_MODELANI_blz_walk4,
    PLAYER_MODELANI_blz_walk5,
    PLAYER_MODELANI_blz_walk6,
    PLAYER_MODELANI_blz_start_01,
    PLAYER_MODELANI_blz_start_02,
    PLAYER_MODELANI_blz_start_03,

    // Blaze's Tail Animations
    PLAYER_MODELANI_blz_t_brake1_01,
    PLAYER_MODELANI_blz_t_brake1_02,
    PLAYER_MODELANI_blz_t_brake1_03,
    PLAYER_MODELANI_blz_t_brake2_01,
    PLAYER_MODELANI_blz_t_brake2_02,
    PLAYER_MODELANI_blz_t_brake2_03,
    PLAYER_MODELANI_blz_t_die_01,
    PLAYER_MODELANI_blz_t_die_02,
    PLAYER_MODELANI_blz_t_dmg_b,
    PLAYER_MODELANI_blz_t_dmg_f,
    PLAYER_MODELANI_blz_t_dush01,
    PLAYER_MODELANI_blz_t_dush02,
    PLAYER_MODELANI_blz_t_fw,
    PLAYER_MODELANI_blz_t_goal,
    PLAYER_MODELANI_blz_t_goal1,
    PLAYER_MODELANI_blz_t_goal2,
    PLAYER_MODELANI_blz_t_graind,
    PLAYER_MODELANI_blz_t_hover,
    PLAYER_MODELANI_blz_t_jump_03,
    PLAYER_MODELANI_blz_t_jump_d,
    PLAYER_MODELANI_blz_t_jump_f_01,
    PLAYER_MODELANI_blz_t_jump_s_01,
    PLAYER_MODELANI_blz_t_jump_s_02,
    PLAYER_MODELANI_blz_t_jump_s_03,
    PLAYER_MODELANI_blz_t_squat,
    PLAYER_MODELANI_blz_t_st_b_01,
    PLAYER_MODELANI_blz_t_st_b_02,
    PLAYER_MODELANI_blz_t_st_f_01,
    PLAYER_MODELANI_blz_t_st_f_02,
    PLAYER_MODELANI_blz_t_tk_001_01,
    PLAYER_MODELANI_blz_t_tk_001_02,
    PLAYER_MODELANI_blz_t_tk_001_03,
    PLAYER_MODELANI_blz_t_tk_001_04,
    PLAYER_MODELANI_blz_t_tk_011_01,
    PLAYER_MODELANI_blz_t_tk_011_02,
    PLAYER_MODELANI_blz_t_tk_021,
    PLAYER_MODELANI_blz_t_tk_031,
    PLAYER_MODELANI_blz_t_tk_041,
    PLAYER_MODELANI_blz_t_tk_051,
    PLAYER_MODELANI_blz_t_tk_061,
    PLAYER_MODELANI_blz_t_tk_071,
    PLAYER_MODELANI_blz_t_tk_081_01,
    PLAYER_MODELANI_blz_t_tk_081_02,
    PLAYER_MODELANI_blz_t_tk_081_03,
    PLAYER_MODELANI_blz_t_touch1_01,
    PLAYER_MODELANI_blz_t_turn01,
    PLAYER_MODELANI_blz_t_up_01,
    PLAYER_MODELANI_blz_t_up_02,
    PLAYER_MODELANI_blz_t_walk1,
    PLAYER_MODELANI_blz_t_walk2,
    PLAYER_MODELANI_blz_t_walk3,
    PLAYER_MODELANI_blz_t_walk4,
    PLAYER_MODELANI_blz_t_walk5,
    PLAYER_MODELANI_blz_t_walk6,
    PLAYER_MODELANI_blz_t_wall_01,
    PLAYER_MODELANI_blz_t_wall_02,
    PLAYER_MODELANI_blz_t_hang_rot,
    PLAYER_MODELANI_blz_t_jump_m_01,
    PLAYER_MODELANI_blz_t_rope_tar,
    PLAYER_MODELANI_blz_t_fan,
    PLAYER_MODELANI_blz_t_wing,
    PLAYER_MODELANI_blz_t_piston_01,
    PLAYER_MODELANI_blz_t_piston_02,
    PLAYER_MODELANI_blz_t_dive_std,
    PLAYER_MODELANI_blz_t_icicle,
    PLAYER_MODELANI_blz_t_anchor,
    PLAYER_MODELANI_blz_t_crane,
    PLAYER_MODELANI_blz_t_iceland,
    PLAYER_MODELANI_blz_t_trmpln,
    PLAYER_MODELANI_blz_t_wg_gun_00,
    PLAYER_MODELANI_blz_t_wg_gun_01,
    PLAYER_MODELANI_blz_t_start_01,
    PLAYER_MODELANI_blz_t_start_02,
    PLAYER_MODELANI_blz_t_start_03,
};

enum PlayerSpriteAnimationID
{
    PLAYER_SPRITEANI_IDLE,
    PLAYER_SPRITEANI_WALK1,
    PLAYER_SPRITEANI_WALK2,
    PLAYER_SPRITEANI_WALK3,
    PLAYER_SPRITEANI_WALK4,
    PLAYER_SPRITEANI_WALK5,
    PLAYER_SPRITEANI_WALK6,
    PLAYER_SPRITEANI_TRICK_FINISH,
    PLAYER_SPRITEANI_UNUSED_8,
    PLAYER_SPRITEANI_JUMPFALL,
    PLAYER_SPRITEANI_DEATH,
    PLAYER_SPRITEANI_HURT,
    PLAYER_SPRITEANI_UNUSED_12,
    PLAYER_SPRITEANI_UNUSED_13,
    PLAYER_SPRITEANI_CROUCH,
    PLAYER_SPRITEANI_SPINDASH,
    PLAYER_SPRITEANI_ROLL,
    PLAYER_SPRITEANI_BALANCE_BACKWARD,
    PLAYER_SPRITEANI_BALANCE_FORWARD,
    PLAYER_SPRITEANI_TURNING,
    PLAYER_SPRITEANI_BRAKE1_02,
    PLAYER_SPRITEANI_BRAKE1_01,
    PLAYER_SPRITEANI_BRAKE2_01,
    PLAYER_SPRITEANI_BRAKE2_02,
    PLAYER_SPRITEANI_BRAKE2_03,
    PLAYER_SPRITEANI_UNUSED_25,
    PLAYER_SPRITEANI_UNUSED_26,
    PLAYER_SPRITEANI_GRIND,
    PLAYER_SPRITEANI_AIRRISE,
    PLAYER_SPRITEANI_AIRFALL_01,
    PLAYER_SPRITEANI_AIRFALL_02,
    PLAYER_SPRITEANI_31,
    PLAYER_SPRITEANI_32,
    PLAYER_SPRITEANI_JUMPDASH_01,
    PLAYER_SPRITEANI_JUMPDASH_02,
    PLAYER_SPRITEANI_UNUSED_35,
    PLAYER_SPRITEANI_UNUSED_36,
};

// TODO: use these in modelAnimForActionSonic/Blaze where appropriate
enum PlayerBoardModelAnimationID
{
    // Common Animations
    PLAYER_BOARDANI_com_bd_dmg,
    PLAYER_BOARDANI_com_bd_fw,
    PLAYER_BOARDANI_com_bd_graind,
    PLAYER_BOARDANI_com_bd_jump01,
    PLAYER_BOARDANI_com_bd_jump02,
    PLAYER_BOARDANI_com_bd_jump03,
    PLAYER_BOARDANI_com_bd_jump_d,
    PLAYER_BOARDANI_com_bd_jump_f_01,
    PLAYER_BOARDANI_com_bd_jump_s_01,
    PLAYER_BOARDANI_com_bd_jump_s_02,
    PLAYER_BOARDANI_com_bd_jump_s_03,
    PLAYER_BOARDANI_com_bd_tk_010,
    PLAYER_BOARDANI_com_bd_tk_011,
    PLAYER_BOARDANI_com_bd_tk_060,
    PLAYER_BOARDANI_com_bd_tk_070,
    PLAYER_BOARDANI_com_bd_tk_080,
    PLAYER_BOARDANI_com_bd_tk_081,
    PLAYER_BOARDANI_com_bd_tk_082,
    PLAYER_BOARDANI_com_bd_walk,

    // Sonic's Animations
    PLAYER_BOARDANI_son_bd_tk_001,
    PLAYER_BOARDANI_son_bd_tk_002,
    PLAYER_BOARDANI_son_bd_tk_020,
    PLAYER_BOARDANI_son_bd_tk_030,
    PLAYER_BOARDANI_son_bd_tk_040,

    // Blaze's Animations
    PLAYER_BOARDANI_blz_bd_tk_001,
    PLAYER_BOARDANI_blz_bd_tk_002,
    PLAYER_BOARDANI_blz_bd_tk_020,
    PLAYER_BOARDANI_blz_bd_tk_030,
    PLAYER_BOARDANI_blz_bd_tk_040,

    // Blaze's Tail Animations
    PLAYER_BOARDANI_blz_t_bd_dmg,
    PLAYER_BOARDANI_blz_t_bd_fw,
    PLAYER_BOARDANI_blz_t_bd_graind,
    PLAYER_BOARDANI_blz_t_bd_jump01,
    PLAYER_BOARDANI_blz_t_bd_jump02,
    PLAYER_BOARDANI_blz_t_bd_jump03,
    PLAYER_BOARDANI_blz_t_bd_jump_d,
    PLAYER_BOARDANI_blz_t_bd_j_f_01,
    PLAYER_BOARDANI_blz_t_bd_j_s_01,
    PLAYER_BOARDANI_blz_t_bd_j_s_02,
    PLAYER_BOARDANI_blz_t_bd_j_s_03,
    PLAYER_BOARDANI_blz_t_bd_tk_001,
    PLAYER_BOARDANI_blz_t_bd_tk_002,
    PLAYER_BOARDANI_blz_t_bd_tk_010,
    PLAYER_BOARDANI_blz_t_bd_tk_011,
    PLAYER_BOARDANI_blz_t_bd_tk_020,
    PLAYER_BOARDANI_blz_t_bd_tk_030,
    PLAYER_BOARDANI_blz_t_bd_tk_040,
    PLAYER_BOARDANI_blz_t_bd_tk_060,
    PLAYER_BOARDANI_blz_t_bd_tk_070,
    PLAYER_BOARDANI_blz_t_bd_tk_080,
    PLAYER_BOARDANI_blz_t_bd_tk_081,
    PLAYER_BOARDANI_blz_t_bd_tk_082,
    PLAYER_BOARDANI_blz_t_bd_walk,
};

// --------------------
// VARIABLES
// --------------------

static u8 const modelAnimForActionSonic[PLAYER_ACTION_COUNT] = {
    PLAYER_MODELANI_com_turn01,       // PLAYER_ACTION_TURNING
    PLAYER_MODELANI_son_fw,           // PLAYER_ACTION_IDLE
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_CROUCH
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_CROUCH_EXIT
    PLAYER_MODELANI_com_brake1_01,    // PLAYER_ACTION_BRAKE1_01
    PLAYER_MODELANI_com_brake1_02,    // PLAYER_ACTION_BRAKE1_02
    PLAYER_MODELANI_com_brake1_03,    // PLAYER_ACTION_BRAKE1_03
    PLAYER_MODELANI_com_brake2_01,    // PLAYER_ACTION_BRAKE2_01
    PLAYER_MODELANI_com_brake2_02,    // PLAYER_ACTION_BRAKE2_02
    PLAYER_MODELANI_com_brake2_03,    // PLAYER_ACTION_BRAKE2_03
    PLAYER_MODELANI_com_wall_01,      // PLAYER_ACTION_PUSH_01
    PLAYER_MODELANI_com_wall_02,      // PLAYER_ACTION_PUSH_02
    PLAYER_MODELANI_com_st_f_02,      // PLAYER_ACTION_BALANCE_FORWARD
    PLAYER_MODELANI_com_st_b_02,      // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYER_MODELANI_com_dmg_b,        // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYER_MODELANI_com_dmg_f,        // PLAYER_ACTION_HURT_TUMBLE
    PLAYER_MODELANI_com_die_01,       // PLAYER_ACTION_DEATH_01
    PLAYER_MODELANI_com_die_02,       // PLAYER_ACTION_DEATH_02
    PLAYER_MODELANI_son_screw,        // PLAYER_ACTION_HOMING_ATTACK
    PLAYER_MODELANI_com_jump_03,      // PLAYER_ACTION_JUMPFALL
    PLAYER_MODELANI_com_jump_s_01,    // PLAYER_ACTION_AIRRISE
    PLAYER_MODELANI_com_jump_s_02,    // PLAYER_ACTION_AIRFALL_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_AIRFALL_02
    PLAYER_MODELANI_com_jump_f_01,    // PLAYER_ACTION_AIRFORWARD_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_AIRFORWARD_02
    PLAYER_MODELANI_com_jump_d,       // PLAYER_ACTION_JUMPDASH_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_JUMPDASH_02
    PLAYER_MODELANI_com_graind,       // PLAYER_ACTION_GRIND
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_1C
    PLAYER_MODELANI_com_tk_061,       // PLAYER_ACTION_GRINDTRICK_1
    PLAYER_MODELANI_com_tk_071,       // PLAYER_ACTION_GRINDTRICK_2
    PLAYER_MODELANI_com_tk_081_01,    // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYER_MODELANI_com_tk_081_02,    // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYER_MODELANI_com_tk_081_03,    // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYER_MODELANI_com_up_01,        // PLAYER_ACTION_LOOKUP_01
    PLAYER_MODELANI_com_up_02,        // PLAYER_ACTION_LOOKUP_02
    PLAYER_MODELANI_son_fw,           // PLAYER_ACTION_24
    PLAYER_MODELANI_com_hang_rot,     // PLAYER_ACTION_HANG_ROT
    PLAYER_MODELANI_com_jump_m_01,    // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYER_MODELANI_com_rope_tar,     // PLAYER_ACTION_ROPE_SWING
    PLAYER_MODELANI_com_graind,       // PLAYER_ACTION_GRIND2
    PLAYER_MODELANI_com_wing,         // PLAYER_ACTION_DREAMWING
    PLAYER_MODELANI_com_piston_01,    // PLAYER_ACTION_PISTON_01
    PLAYER_MODELANI_com_piston_02,    // PLAYER_ACTION_PISTON_02
    PLAYER_MODELANI_com_fan,          // PLAYER_ACTION_STEAM_FAN
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_2D
    PLAYER_MODELANI_com_icicle,       // PLAYER_ACTION_ICICLE
    PLAYER_MODELANI_com_iceland,      // PLAYER_ACTION_ICE_SLIDE
    PLAYER_MODELANI_com_iceland,      // PLAYER_ACTION_30
    PLAYER_MODELANI_com_dive_std,     // PLAYER_ACTION_DIVING_BOARD
    PLAYER_MODELANI_com_crane,        // PLAYER_ACTION_CRANE
    PLAYER_MODELANI_com_anchor,       // PLAYER_ACTION_ANCHOR_ROPE
    PLAYER_MODELANI_son_start_01,     // PLAYER_ACTION_START_01
    PLAYER_MODELANI_son_start_02,     // PLAYER_ACTION_START_02
    PLAYER_MODELANI_son_start_03,     // PLAYER_ACTION_START_03
    PLAYER_MODELANI_com_trmpln,       // PLAYER_ACTION_TRAMPOLINE
    PLAYER_MODELANI_com_anchor,       // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYER_MODELANI_com_fan,          // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYER_MODELANI_com_crane,        // PLAYER_ACTION_BALLOON_RIDE
    PLAYER_MODELANI_com_wg_gun_00,    // PLAYER_ACTION_WATERGUN_01
    PLAYER_MODELANI_com_wg_gun_01,    // PLAYER_ACTION_WATERGUN_02
    PLAYER_MODELANI_com_jump_s_01,    // PLAYER_ACTION_3D
    PLAYER_BOARDANI_com_bd_fw,        // PLAYER_ACTION_START_SNOWBOARD
    PLAYER_BOARDANI_com_bd_walk,      // PLAYER_ACTION_3F
    PLAYER_BOARDANI_com_bd_fw,        // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYER_BOARDANI_com_bd_walk,      // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump01,    // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump02,    // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump03,    // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYER_BOARDANI_son_bd_tk_001,    // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYER_BOARDANI_son_bd_tk_002,    // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_tk_010,    // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_tk_011,    // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_d,    // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYER_BOARDANI_son_bd_tk_020,    // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYER_BOARDANI_son_bd_tk_030,    // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYER_BOARDANI_son_bd_tk_040,    // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump_s_01, // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump_s_02, // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_f_01, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_d,    // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_graind,    // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYER_BOARDANI_com_bd_tk_060,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYER_BOARDANI_com_bd_tk_070,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYER_BOARDANI_com_bd_tk_080,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYER_BOARDANI_com_bd_tk_081,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYER_BOARDANI_com_bd_tk_082,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYER_BOARDANI_com_bd_dmg,       // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYER_MODELANI_com_dive_std,     // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYER_MODELANI_son_screw,        // PLAYER_ACTION_ROLL
    PLAYER_MODELANI_son_screw,        // PLAYER_ACTION_SPINDASH
    PLAYER_MODELANI_son_screw,        // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYER_MODELANI_blz_hover,        // PLAYER_ACTION_FLAMEHOVER
    PLAYER_MODELANI_son_tk_001_01,    // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYER_MODELANI_son_tk_001_02,    // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYER_MODELANI_son_tk_001_03,    // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYER_MODELANI_son_tk_001_04,    // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYER_MODELANI_son_tk_011_01,    // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYER_MODELANI_son_tk_011_02,    // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYER_MODELANI_com_tk_051,       // PLAYER_ACTION_RAINBOWDASHRING
    PLAYER_MODELANI_son_tk_021,       // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYER_MODELANI_son_tk_031,       // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYER_MODELANI_son_tk_041,       // PLAYER_ACTION_TRICK_FINISH
    PLAYER_MODELANI_son_walk1,        // PLAYER_ACTION_WALK1
    PLAYER_MODELANI_son_walk2,        // PLAYER_ACTION_WALK2
    PLAYER_MODELANI_son_walk3,        // PLAYER_ACTION_WALK3
    PLAYER_MODELANI_son_walk4,        // PLAYER_ACTION_WALK4
    PLAYER_MODELANI_son_walk5,        // PLAYER_ACTION_WALK5
    PLAYER_MODELANI_son_walk6,        // PLAYER_ACTION_WALK6
    PLAYER_MODELANI_son_goal1,        // PLAYER_ACTION_GOAL1
    PLAYER_MODELANI_son_goal2,        // PLAYER_ACTION_GOAL2
    PLAYER_MODELANI_son_touch1,       // PLAYER_ACTION_TOUCH_REACT
    PLAYER_MODELANI_son_touch1,       // PLAYER_ACTION_73
    PLAYER_MODELANI_son_touch1,       // PLAYER_ACTION_74
    PLAYER_MODELANI_son_fw,           // PLAYER_ACTION_75
    PLAYER_MODELANI_son_fw,           // PLAYER_ACTION_76
    PLAYER_MODELANI_son_fw,           // PLAYER_ACTION_77
    PLAYER_MODELANI_com_die_02,       // PLAYER_ACTION_BOSS5FREEZE
    PLAYER_MODELANI_son_walk6         // PLAYER_ACTION_BOSS6_RUN
};

static u8 const spriteAnimForActionBlaze[PLAYER_ACTION_COUNT] = {
    PLAYER_SPRITEANI_TURNING,          // PLAYER_ACTION_TURNING
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_IDLE
    PLAYER_SPRITEANI_CROUCH,           // PLAYER_ACTION_CROUCH
    PLAYER_SPRITEANI_SPINDASH,         // PLAYER_ACTION_CROUCH_EXIT
    PLAYER_SPRITEANI_BRAKE1_01,        // PLAYER_ACTION_BRAKE1_01
    PLAYER_SPRITEANI_BRAKE1_02,        // PLAYER_ACTION_BRAKE1_02
    PLAYER_SPRITEANI_BRAKE1_01,        // PLAYER_ACTION_BRAKE1_03
    PLAYER_SPRITEANI_BRAKE2_01,        // PLAYER_ACTION_BRAKE2_01
    PLAYER_SPRITEANI_BRAKE2_02,        // PLAYER_ACTION_BRAKE2_02
    PLAYER_SPRITEANI_BRAKE2_03,        // PLAYER_ACTION_BRAKE2_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PUSH_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PUSH_02
    PLAYER_SPRITEANI_BALANCE_FORWARD,  // PLAYER_ACTION_BALANCE_FORWARD
    PLAYER_SPRITEANI_BALANCE_BACKWARD, // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_TUMBLE
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_DEATH_01
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_DEATH_02
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_HOMING_ATTACK
    PLAYER_SPRITEANI_JUMPFALL,         // PLAYER_ACTION_JUMPFALL
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_AIRRISE
    PLAYER_SPRITEANI_AIRFALL_01,       // PLAYER_ACTION_AIRFALL_01
    PLAYER_SPRITEANI_AIRFALL_02,       // PLAYER_ACTION_AIRFALL_02
    PLAYER_SPRITEANI_31,               // PLAYER_ACTION_AIRFORWARD_01
    PLAYER_SPRITEANI_32,               // PLAYER_ACTION_AIRFORWARD_02
    PLAYER_SPRITEANI_JUMPDASH_01,      // PLAYER_ACTION_JUMPDASH_01
    PLAYER_SPRITEANI_JUMPDASH_02,      // PLAYER_ACTION_JUMPDASH_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_1C
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_1
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_2
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_LOOKUP_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_LOOKUP_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_24
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_HANG_ROT
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ROPE_SWING
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND2
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DREAMWING
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PISTON_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PISTON_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_STEAM_FAN
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_2D
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ICICLE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ICE_SLIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_30
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DIVING_BOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_CRANE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ANCHOR_ROPE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_TRAMPOLINE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_BALLOON_RIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WATERGUN_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WATERGUN_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_3D
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_3F
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYER_SPRITEANI_AIRFALL_01,       // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYER_SPRITEANI_AIRFALL_02,       // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYER_SPRITEANI_31,               // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYER_SPRITEANI_32,               // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYER_SPRITEANI_JUMPDASH_01,      // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYER_SPRITEANI_JUMPDASH_02,      // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYER_SPRITEANI_ROLL,             // PLAYER_ACTION_ROLL
    PLAYER_SPRITEANI_SPINDASH,         // PLAYER_ACTION_SPINDASH
    PLAYER_SPRITEANI_SPINDASH,         // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_FLAMEHOVER
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_RAINBOWDASHRING
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH
    PLAYER_SPRITEANI_WALK1,            // PLAYER_ACTION_WALK1
    PLAYER_SPRITEANI_WALK2,            // PLAYER_ACTION_WALK2
    PLAYER_SPRITEANI_WALK3,            // PLAYER_ACTION_WALK3
    PLAYER_SPRITEANI_WALK4,            // PLAYER_ACTION_WALK4
    PLAYER_SPRITEANI_WALK5,            // PLAYER_ACTION_WALK5
    PLAYER_SPRITEANI_WALK6,            // PLAYER_ACTION_WALK6
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_GOAL1
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_GOAL2
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_TOUCH_REACT
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_73
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_74
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_75
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_76
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_77
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_BOSS5FREEZE
    PLAYER_SPRITEANI_WALK6             // PLAYER_ACTION_BOSS6_RUN
};

static u8 const modelIndexForActionSonic[PLAYER_ACTION_COUNT] = {
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TURNING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_IDLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CROUCH
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CROUCH_EXIT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PUSH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PUSH_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALANCE_FORWARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_TUMBLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DEATH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DEATH_02
    PLAYERMODEL_BALL,   // PLAYER_ACTION_HOMING_ATTACK
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPFALL
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRRISE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_1C
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_LOOKUP_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_LOOKUP_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_24
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HANG_ROT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ROPE_SWING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DREAMWING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PISTON_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PISTON_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_STEAM_FAN
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_2D
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ICICLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ICE_SLIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_30
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DIVING_BOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CRANE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ANCHOR_ROPE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRAMPOLINE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALLOON_RIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WATERGUN_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WATERGUN_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_3D
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_3F
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYERMODEL_BALL,   // PLAYER_ACTION_ROLL
    PLAYERMODEL_BALL,   // PLAYER_ACTION_SPINDASH
    PLAYERMODEL_BALL,   // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYERMODEL_BALL,   // PLAYER_ACTION_FLAMEHOVER
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_RAINBOWDASHRING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK3
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK4
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK5
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK6
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GOAL1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GOAL2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TOUCH_REACT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_73
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_74
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_75
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_76
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_77
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BOSS5FREEZE
    PLAYERMODEL_PLAYER  // PLAYER_ACTION_BOSS6_RUN
};

static u8 const modelIndexForActionBlaze[PLAYER_ACTION_COUNT] = {
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TURNING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_IDLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CROUCH
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CROUCH_EXIT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE1_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BRAKE2_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PUSH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PUSH_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALANCE_FORWARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_TUMBLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DEATH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DEATH_02
    PLAYERMODEL_BALL,   // PLAYER_ACTION_HOMING_ATTACK
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPFALL
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRRISE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_1C
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_LOOKUP_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_LOOKUP_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_24
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HANG_ROT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ROPE_SWING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DREAMWING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PISTON_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_PISTON_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_STEAM_FAN
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_2D
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ICICLE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ICE_SLIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_30
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DIVING_BOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_CRANE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_ANCHOR_ROPE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRAMPOLINE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BALLOON_RIDE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WATERGUN_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WATERGUN_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_3D
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_START_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_3F
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYERMODEL_BALL,   // PLAYER_ACTION_ROLL
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_SPINDASH
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_FLAMEHOVER
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_RAINBOWDASHRING
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TRICK_FINISH
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK3
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK4
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK5
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_WALK6
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GOAL1
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_GOAL2
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_TOUCH_REACT
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_73
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_74
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_75
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_76
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_77
    PLAYERMODEL_PLAYER, // PLAYER_ACTION_BOSS5FREEZE
    PLAYERMODEL_PLAYER  // PLAYER_ACTION_BOSS6_RUN
};

static u8 const spriteAnimForActionSonic[PLAYER_ACTION_COUNT] = {
    PLAYER_SPRITEANI_TURNING,          // PLAYER_ACTION_TURNING
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_IDLE
    PLAYER_SPRITEANI_CROUCH,           // PLAYER_ACTION_CROUCH
    PLAYER_SPRITEANI_SPINDASH,         // PLAYER_ACTION_CROUCH_EXIT
    PLAYER_SPRITEANI_BRAKE1_01,        // PLAYER_ACTION_BRAKE1_01
    PLAYER_SPRITEANI_BRAKE1_02,        // PLAYER_ACTION_BRAKE1_02
    PLAYER_SPRITEANI_BRAKE1_01,        // PLAYER_ACTION_BRAKE1_03
    PLAYER_SPRITEANI_BRAKE2_01,        // PLAYER_ACTION_BRAKE2_01
    PLAYER_SPRITEANI_BRAKE2_02,        // PLAYER_ACTION_BRAKE2_02
    PLAYER_SPRITEANI_BRAKE2_03,        // PLAYER_ACTION_BRAKE2_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PUSH_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PUSH_02
    PLAYER_SPRITEANI_BALANCE_FORWARD,  // PLAYER_ACTION_BALANCE_FORWARD
    PLAYER_SPRITEANI_BALANCE_BACKWARD, // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_TUMBLE
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_DEATH_01
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_DEATH_02
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_HOMING_ATTACK
    PLAYER_SPRITEANI_JUMPFALL,         // PLAYER_ACTION_JUMPFALL
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_AIRRISE
    PLAYER_SPRITEANI_AIRFALL_01,       // PLAYER_ACTION_AIRFALL_01
    PLAYER_SPRITEANI_AIRFALL_02,       // PLAYER_ACTION_AIRFALL_02
    PLAYER_SPRITEANI_31,               // PLAYER_ACTION_AIRFORWARD_01
    PLAYER_SPRITEANI_32,               // PLAYER_ACTION_AIRFORWARD_02
    PLAYER_SPRITEANI_JUMPDASH_01,      // PLAYER_ACTION_JUMPDASH_01
    PLAYER_SPRITEANI_JUMPDASH_02,      // PLAYER_ACTION_JUMPDASH_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_1C
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_1
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_2
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_LOOKUP_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_LOOKUP_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_24
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_HANG_ROT
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ROPE_SWING
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND2
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DREAMWING
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PISTON_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_PISTON_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_STEAM_FAN
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_2D
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ICICLE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ICE_SLIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_30
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DIVING_BOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_CRANE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_ANCHOR_ROPE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_03
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_TRAMPOLINE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_BALLOON_RIDE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WATERGUN_01
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WATERGUN_02
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_3D
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_START_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_3F
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYER_SPRITEANI_JUMPFALL,         // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYER_SPRITEANI_JUMPFALL,         // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYER_SPRITEANI_JUMPFALL,         // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYER_SPRITEANI_AIRFALL_01,       // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYER_SPRITEANI_AIRFALL_02,       // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYER_SPRITEANI_31,               // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYER_SPRITEANI_32,               // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYER_SPRITEANI_JUMPDASH_01,      // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYER_SPRITEANI_JUMPDASH_02,      // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYER_SPRITEANI_GRIND,            // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYER_SPRITEANI_HURT,             // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYER_SPRITEANI_ROLL,             // PLAYER_ACTION_ROLL
    PLAYER_SPRITEANI_ROLL,             // PLAYER_ACTION_SPINDASH
    PLAYER_SPRITEANI_ROLL,             // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_FLAMEHOVER
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYER_SPRITEANI_TRICK_FINISH,     // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_RAINBOWDASHRING
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYER_SPRITEANI_AIRRISE,          // PLAYER_ACTION_TRICK_FINISH
    PLAYER_SPRITEANI_WALK1,            // PLAYER_ACTION_WALK1
    PLAYER_SPRITEANI_WALK2,            // PLAYER_ACTION_WALK2
    PLAYER_SPRITEANI_WALK3,            // PLAYER_ACTION_WALK3
    PLAYER_SPRITEANI_WALK4,            // PLAYER_ACTION_WALK4
    PLAYER_SPRITEANI_WALK5,            // PLAYER_ACTION_WALK5
    PLAYER_SPRITEANI_WALK6,            // PLAYER_ACTION_WALK6
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_GOAL1
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_GOAL2
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_TOUCH_REACT
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_73
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_74
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_75
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_76
    PLAYER_SPRITEANI_IDLE,             // PLAYER_ACTION_77
    PLAYER_SPRITEANI_DEATH,            // PLAYER_ACTION_BOSS5FREEZE
    PLAYER_SPRITEANI_WALK6             // PLAYER_ACTION_BOSS6_RUN
};

static u8 const tailAnimForActionBlaze[PLAYER_ACTION_COUNT] = {
    PLAYER_MODELANI_blz_t_turn01,    // PLAYER_ACTION_TURNING
    PLAYER_MODELANI_blz_t_fw,        // PLAYER_ACTION_IDLE
    PLAYER_MODELANI_blz_t_squat,     // PLAYER_ACTION_CROUCH
    PLAYER_MODELANI_blz_t_squat,     // PLAYER_ACTION_CROUCH_EXIT
    PLAYER_MODELANI_blz_t_brake1_01, // PLAYER_ACTION_BRAKE1_01
    PLAYER_MODELANI_blz_t_brake1_02, // PLAYER_ACTION_BRAKE1_02
    PLAYER_MODELANI_blz_t_brake1_03, // PLAYER_ACTION_BRAKE1_03
    PLAYER_MODELANI_blz_t_brake2_01, // PLAYER_ACTION_BRAKE2_01
    PLAYER_MODELANI_blz_t_brake2_02, // PLAYER_ACTION_BRAKE2_02
    PLAYER_MODELANI_blz_t_brake2_03, // PLAYER_ACTION_BRAKE2_03
    PLAYER_MODELANI_blz_t_wall_01,   // PLAYER_ACTION_PUSH_01
    PLAYER_MODELANI_blz_t_wall_02,   // PLAYER_ACTION_PUSH_02
    PLAYER_MODELANI_blz_t_st_f_02,   // PLAYER_ACTION_BALANCE_FORWARD
    PLAYER_MODELANI_blz_t_st_b_02,   // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYER_MODELANI_blz_t_dmg_b,     // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYER_MODELANI_blz_t_dmg_f,     // PLAYER_ACTION_HURT_TUMBLE
    PLAYER_MODELANI_blz_t_die_01,    // PLAYER_ACTION_DEATH_01
    PLAYER_MODELANI_blz_t_die_02,    // PLAYER_ACTION_DEATH_02
    PLAYER_ANIM_NONE,                // PLAYER_ACTION_HOMING_ATTACK
    PLAYER_MODELANI_blz_t_jump_03,   // PLAYER_ACTION_JUMPFALL
    PLAYER_MODELANI_blz_t_jump_s_01, // PLAYER_ACTION_AIRRISE
    PLAYER_MODELANI_blz_t_jump_s_02, // PLAYER_ACTION_AIRFALL_01
    PLAYER_MODELANI_blz_t_jump_s_03, // PLAYER_ACTION_AIRFALL_02
    PLAYER_MODELANI_blz_t_jump_f_01, // PLAYER_ACTION_AIRFORWARD_01
    PLAYER_MODELANI_blz_t_jump_s_03, // PLAYER_ACTION_AIRFORWARD_02
    PLAYER_MODELANI_blz_t_jump_d,    // PLAYER_ACTION_JUMPDASH_01
    PLAYER_MODELANI_blz_t_jump_s_03, // PLAYER_ACTION_JUMPDASH_02
    PLAYER_MODELANI_blz_t_graind,    // PLAYER_ACTION_GRIND
    PLAYER_MODELANI_blz_t_squat,     // PLAYER_ACTION_1C
    PLAYER_MODELANI_blz_t_tk_061,    // PLAYER_ACTION_GRINDTRICK_1
    PLAYER_MODELANI_blz_t_tk_071,    // PLAYER_ACTION_GRINDTRICK_2
    PLAYER_MODELANI_blz_t_tk_081_01, // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYER_MODELANI_blz_t_tk_081_02, // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYER_MODELANI_blz_t_tk_081_03, // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYER_MODELANI_blz_t_up_01,     // PLAYER_ACTION_LOOKUP_01
    PLAYER_MODELANI_blz_t_up_02,     // PLAYER_ACTION_LOOKUP_02
    PLAYER_MODELANI_blz_t_fw,        // PLAYER_ACTION_24
    PLAYER_MODELANI_blz_t_hang_rot,  // PLAYER_ACTION_HANG_ROT
    PLAYER_MODELANI_blz_t_jump_m_01, // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYER_MODELANI_blz_t_rope_tar,  // PLAYER_ACTION_ROPE_SWING
    PLAYER_MODELANI_blz_t_graind,    // PLAYER_ACTION_GRIND2
    PLAYER_MODELANI_blz_t_wing,      // PLAYER_ACTION_DREAMWING
    PLAYER_MODELANI_blz_t_piston_01, // PLAYER_ACTION_PISTON_01
    PLAYER_MODELANI_blz_t_piston_02, // PLAYER_ACTION_PISTON_02
    PLAYER_MODELANI_blz_t_fan,       // PLAYER_ACTION_STEAM_FAN
    PLAYER_MODELANI_blz_t_squat,     // PLAYER_ACTION_2D
    PLAYER_MODELANI_blz_t_icicle,    // PLAYER_ACTION_ICICLE
    PLAYER_MODELANI_blz_t_iceland,   // PLAYER_ACTION_ICE_SLIDE
    PLAYER_MODELANI_blz_t_iceland,   // PLAYER_ACTION_30
    PLAYER_MODELANI_blz_t_dive_std,  // PLAYER_ACTION_DIVING_BOARD
    PLAYER_MODELANI_blz_t_crane,     // PLAYER_ACTION_CRANE
    PLAYER_MODELANI_blz_t_anchor,    // PLAYER_ACTION_ANCHOR_ROPE
    PLAYER_MODELANI_blz_t_start_01,  // PLAYER_ACTION_START_01
    PLAYER_MODELANI_blz_t_start_02,  // PLAYER_ACTION_START_02
    PLAYER_MODELANI_blz_t_start_03,  // PLAYER_ACTION_START_03
    PLAYER_MODELANI_blz_t_trmpln,    // PLAYER_ACTION_TRAMPOLINE
    PLAYER_MODELANI_blz_t_anchor,    // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYER_MODELANI_blz_t_fan,       // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYER_MODELANI_blz_t_crane,     // PLAYER_ACTION_BALLOON_RIDE
    PLAYER_MODELANI_blz_t_wg_gun_00, // PLAYER_ACTION_WATERGUN_01
    PLAYER_MODELANI_blz_t_wg_gun_01, // PLAYER_ACTION_WATERGUN_02
    PLAYER_MODELANI_blz_t_jump_s_01, // PLAYER_ACTION_3D
    PLAYER_BOARDANI_blz_t_bd_fw,     // PLAYER_ACTION_START_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_walk,   // PLAYER_ACTION_3F
    PLAYER_BOARDANI_blz_t_bd_fw,     // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_walk,   // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_jump01, // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_jump02, // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_jump03, // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_tk_001, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_tk_002, // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_tk_010, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_tk_011, // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_jump_d, // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_tk_020, // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_tk_030, // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_tk_040, // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_j_s_01, // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_j_s_02, // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_j_s_03, // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_j_f_01, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_j_s_03, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_jump_d, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYER_BOARDANI_blz_t_bd_j_s_03, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYER_BOARDANI_blz_t_bd_graind, // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYER_BOARDANI_blz_t_bd_tk_060, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYER_BOARDANI_blz_t_bd_tk_070, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYER_BOARDANI_blz_t_bd_tk_080, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYER_BOARDANI_blz_t_bd_tk_081, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYER_BOARDANI_blz_t_bd_tk_082, // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYER_BOARDANI_blz_t_bd_dmg,    // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYER_MODELANI_blz_t_dive_std,  // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYER_ANIM_NONE,                // PLAYER_ACTION_ROLL
    PLAYER_MODELANI_blz_t_dush01,    // PLAYER_ACTION_SPINDASH
    PLAYER_MODELANI_blz_t_dush02,    // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYER_MODELANI_blz_t_hover,     // PLAYER_ACTION_FLAMEHOVER
    PLAYER_MODELANI_blz_t_tk_001_01, // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYER_MODELANI_blz_t_tk_001_02, // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYER_MODELANI_blz_t_tk_001_03, // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYER_MODELANI_blz_t_tk_001_04, // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYER_MODELANI_blz_t_tk_011_01, // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYER_MODELANI_blz_t_tk_011_02, // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYER_MODELANI_blz_t_tk_051,    // PLAYER_ACTION_RAINBOWDASHRING
    PLAYER_MODELANI_blz_t_tk_021,    // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYER_MODELANI_blz_t_tk_031,    // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYER_MODELANI_blz_t_tk_041,    // PLAYER_ACTION_TRICK_FINISH
    PLAYER_MODELANI_blz_t_walk1,     // PLAYER_ACTION_WALK1
    PLAYER_MODELANI_blz_t_walk2,     // PLAYER_ACTION_WALK2
    PLAYER_MODELANI_blz_t_walk3,     // PLAYER_ACTION_WALK3
    PLAYER_MODELANI_blz_t_walk4,     // PLAYER_ACTION_WALK4
    PLAYER_MODELANI_blz_t_walk5,     // PLAYER_ACTION_WALK5
    PLAYER_MODELANI_blz_t_walk6,     // PLAYER_ACTION_WALK6
    PLAYER_MODELANI_blz_t_goal1,     // PLAYER_ACTION_GOAL1
    PLAYER_MODELANI_blz_t_goal2,     // PLAYER_ACTION_GOAL2
    PLAYER_MODELANI_blz_t_touch1_01, // PLAYER_ACTION_TOUCH_REACT
    PLAYER_MODELANI_blz_t_touch1_01, // PLAYER_ACTION_73
    PLAYER_MODELANI_blz_t_touch1_01, // PLAYER_ACTION_74
    PLAYER_MODELANI_blz_t_fw,        // PLAYER_ACTION_75
    PLAYER_MODELANI_blz_t_fw,        // PLAYER_ACTION_76
    PLAYER_MODELANI_blz_t_fw,        // PLAYER_ACTION_77
    PLAYER_MODELANI_blz_t_die_02,    // PLAYER_ACTION_BOSS5FREEZE
    PLAYER_MODELANI_blz_t_walk6      // PLAYER_ACTION_BOSS6_RUN
};

static u8 const modelAnimForActionBlaze[PLAYER_ACTION_COUNT] = {
    PLAYER_MODELANI_com_turn01,       // PLAYER_ACTION_TURNING
    PLAYER_MODELANI_blz_fw,           // PLAYER_ACTION_IDLE
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_CROUCH
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_CROUCH_EXIT
    PLAYER_MODELANI_com_brake1_01,    // PLAYER_ACTION_BRAKE1_01
    PLAYER_MODELANI_com_brake1_02,    // PLAYER_ACTION_BRAKE1_02
    PLAYER_MODELANI_com_brake1_03,    // PLAYER_ACTION_BRAKE1_03
    PLAYER_MODELANI_com_brake2_01,    // PLAYER_ACTION_BRAKE2_01
    PLAYER_MODELANI_com_brake2_02,    // PLAYER_ACTION_BRAKE2_02
    PLAYER_MODELANI_com_brake2_03,    // PLAYER_ACTION_BRAKE2_03
    PLAYER_MODELANI_com_wall_01,      // PLAYER_ACTION_PUSH_01
    PLAYER_MODELANI_com_wall_02,      // PLAYER_ACTION_PUSH_02
    PLAYER_MODELANI_com_st_f_02,      // PLAYER_ACTION_BALANCE_FORWARD
    PLAYER_MODELANI_com_st_b_02,      // PLAYER_ACTION_BALANCE_BACKWARD
    PLAYER_MODELANI_com_dmg_b,        // PLAYER_ACTION_HURT_KNOCKBACK
    PLAYER_MODELANI_com_dmg_f,        // PLAYER_ACTION_HURT_TUMBLE
    PLAYER_MODELANI_com_die_01,       // PLAYER_ACTION_DEATH_01
    PLAYER_MODELANI_com_die_02,       // PLAYER_ACTION_DEATH_02
    PLAYER_MODELANI_blz_ball,         // PLAYER_ACTION_HOMING_ATTACK
    PLAYER_MODELANI_com_jump_03,      // PLAYER_ACTION_JUMPFALL
    PLAYER_MODELANI_com_jump_s_01,    // PLAYER_ACTION_AIRRISE
    PLAYER_MODELANI_com_jump_s_02,    // PLAYER_ACTION_AIRFALL_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_AIRFALL_02
    PLAYER_MODELANI_com_jump_f_01,    // PLAYER_ACTION_AIRFORWARD_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_AIRFORWARD_02
    PLAYER_MODELANI_com_jump_d,       // PLAYER_ACTION_JUMPDASH_01
    PLAYER_MODELANI_com_jump_s_03,    // PLAYER_ACTION_JUMPDASH_02
    PLAYER_MODELANI_com_graind,       // PLAYER_ACTION_GRIND
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_1C
    PLAYER_MODELANI_com_tk_061,       // PLAYER_ACTION_GRINDTRICK_1
    PLAYER_MODELANI_com_tk_071,       // PLAYER_ACTION_GRINDTRICK_2
    PLAYER_MODELANI_com_tk_081_01,    // PLAYER_ACTION_GRINDTRICK_3_01
    PLAYER_MODELANI_com_tk_081_02,    // PLAYER_ACTION_GRINDTRICK_3_02
    PLAYER_MODELANI_com_tk_081_03,    // PLAYER_ACTION_GRINDTRICK_3_03
    PLAYER_MODELANI_com_up_01,        // PLAYER_ACTION_LOOKUP_01
    PLAYER_MODELANI_com_up_02,        // PLAYER_ACTION_LOOKUP_02
    PLAYER_MODELANI_blz_fw,           // PLAYER_ACTION_24
    PLAYER_MODELANI_com_hang_rot,     // PLAYER_ACTION_HANG_ROT
    PLAYER_MODELANI_com_jump_m_01,    // PLAYER_ACTION_MUSHROOM_BOUNCE
    PLAYER_MODELANI_com_rope_tar,     // PLAYER_ACTION_ROPE_SWING
    PLAYER_MODELANI_com_graind,       // PLAYER_ACTION_GRIND2
    PLAYER_MODELANI_com_wing,         // PLAYER_ACTION_DREAMWING
    PLAYER_MODELANI_com_piston_01,    // PLAYER_ACTION_PISTON_01
    PLAYER_MODELANI_com_piston_02,    // PLAYER_ACTION_PISTON_02
    PLAYER_MODELANI_com_fan,          // PLAYER_ACTION_STEAM_FAN
    PLAYER_MODELANI_com_squat,        // PLAYER_ACTION_2D
    PLAYER_MODELANI_com_icicle,       // PLAYER_ACTION_ICICLE
    PLAYER_MODELANI_com_iceland,      // PLAYER_ACTION_ICE_SLIDE
    PLAYER_MODELANI_com_iceland,      // PLAYER_ACTION_30
    PLAYER_MODELANI_com_dive_std,     // PLAYER_ACTION_DIVING_BOARD
    PLAYER_MODELANI_com_crane,        // PLAYER_ACTION_CRANE
    PLAYER_MODELANI_com_anchor,       // PLAYER_ACTION_ANCHOR_ROPE
    PLAYER_MODELANI_blz_start_01,     // PLAYER_ACTION_START_01
    PLAYER_MODELANI_blz_start_02,     // PLAYER_ACTION_START_02
    PLAYER_MODELANI_blz_start_03,     // PLAYER_ACTION_START_03
    PLAYER_MODELANI_com_trmpln,       // PLAYER_ACTION_TRAMPOLINE
    PLAYER_MODELANI_com_anchor,       // PLAYER_ACTION_DOLPHIN_RIDE
    PLAYER_MODELANI_com_fan,          // PLAYER_ACTION_HOVER_CRYSTAL
    PLAYER_MODELANI_com_crane,        // PLAYER_ACTION_BALLOON_RIDE
    PLAYER_MODELANI_com_wg_gun_00,    // PLAYER_ACTION_WATERGUN_01
    PLAYER_MODELANI_com_wg_gun_01,    // PLAYER_ACTION_WATERGUN_02
    PLAYER_MODELANI_com_jump_s_01,    // PLAYER_ACTION_3D
    PLAYER_BOARDANI_com_bd_fw,        // PLAYER_ACTION_START_SNOWBOARD
    PLAYER_BOARDANI_com_bd_walk,      // PLAYER_ACTION_3F
    PLAYER_BOARDANI_com_bd_fw,        // PLAYER_ACTION_IDLE_SNOWBOARD
    PLAYER_BOARDANI_com_bd_walk,      // PLAYER_ACTION_WALK_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump01,    // PLAYER_ACTION_JUMP_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump02,    // PLAYER_ACTION_JUMP_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump03,    // PLAYER_ACTION_JUMPFALL_SNOWBOARD
    PLAYER_BOARDANI_blz_bd_tk_001,    // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_01
    PLAYER_BOARDANI_blz_bd_tk_002,    // PLAYER_ACTION_TRICK_FINISH_V_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_tk_010,    // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_tk_011,    // PLAYER_ACTION_TRICK_FINISH_H_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_d,    // PLAYER_ACTION_RAINBOWDASHRING_SNOWBOARD
    PLAYER_BOARDANI_blz_bd_tk_020,    // PLAYER_ACTION_TRICK_SUCCESS1_SNOWBOARD
    PLAYER_BOARDANI_blz_bd_tk_030,    // PLAYER_ACTION_TRICK_SUCCESS2_SNOWBOARD
    PLAYER_BOARDANI_blz_bd_tk_040,    // PLAYER_ACTION_TRICK_FINISH_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump_s_01, // PLAYER_ACTION_AIRRISE_SNOWBOARD
    PLAYER_BOARDANI_com_bd_jump_s_02, // PLAYER_ACTION_AIRFALL_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_AIRFALL_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_f_01, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_AIRFORWARD_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_jump_d,    // PLAYER_ACTION_JUMPDASH_SNOWBOARD_01
    PLAYER_BOARDANI_com_bd_jump_s_03, // PLAYER_ACTION_JUMPDASH_SNOWBOARD_02
    PLAYER_BOARDANI_com_bd_graind,    // PLAYER_ACTION_GRIND_SNOWBOARD
    PLAYER_BOARDANI_com_bd_tk_060,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_1
    PLAYER_BOARDANI_com_bd_tk_070,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_2
    PLAYER_BOARDANI_com_bd_tk_080,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_01
    PLAYER_BOARDANI_com_bd_tk_081,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_02
    PLAYER_BOARDANI_com_bd_tk_082,    // PLAYER_ACTION_GRINDTRICK_SNOWBOARD_3_03
    PLAYER_BOARDANI_com_bd_dmg,       // PLAYER_ACTION_HURT_SNOWBOARD
    PLAYER_MODELANI_com_dive_std,     // PLAYER_ACTION_DIVING_BOARD_SNOWBOARD
    PLAYER_MODELANI_blz_ball,         // PLAYER_ACTION_ROLL
    PLAYER_MODELANI_blz_dush1,        // PLAYER_ACTION_SPINDASH
    PLAYER_MODELANI_blz_dush2,        // PLAYER_ACTION_SPINDASH_CHARGE
    PLAYER_MODELANI_blz_hover,        // PLAYER_ACTION_FLAMEHOVER
    PLAYER_MODELANI_blz_tk_001_01,    // PLAYER_ACTION_TRICK_FINISH_V_01
    PLAYER_MODELANI_blz_tk_001_02,    // PLAYER_ACTION_TRICK_FINISH_V_02
    PLAYER_MODELANI_blz_tk_001_03,    // PLAYER_ACTION_TRICK_FINISH_V_03
    PLAYER_MODELANI_blz_tk_001_04,    // PLAYER_ACTION_TRICK_FINISH_V_04
    PLAYER_MODELANI_blz_tk_011_01,    // PLAYER_ACTION_TRICK_FINISH_H_01
    PLAYER_MODELANI_blz_tk_011_02,    // PLAYER_ACTION_TRICK_FINISH_H_02
    PLAYER_MODELANI_com_tk_051,       // PLAYER_ACTION_RAINBOWDASHRING
    PLAYER_MODELANI_blz_tk_021,       // PLAYER_ACTION_TRICK_SUCCESS1
    PLAYER_MODELANI_blz_tk_031,       // PLAYER_ACTION_TRICK_SUCCESS2
    PLAYER_MODELANI_blz_tk_041,       // PLAYER_ACTION_TRICK_FINISH
    PLAYER_MODELANI_blz_walk1,        // PLAYER_ACTION_WALK1
    PLAYER_MODELANI_blz_walk2,        // PLAYER_ACTION_WALK2
    PLAYER_MODELANI_blz_walk3,        // PLAYER_ACTION_WALK3
    PLAYER_MODELANI_blz_walk4,        // PLAYER_ACTION_WALK4
    PLAYER_MODELANI_blz_walk5,        // PLAYER_ACTION_WALK5
    PLAYER_MODELANI_blz_walk6,        // PLAYER_ACTION_WALK6
    PLAYER_MODELANI_blz_goal1,        // PLAYER_ACTION_GOAL1
    PLAYER_MODELANI_blz_goal2,        // PLAYER_ACTION_GOAL2
    PLAYER_MODELANI_blz_touch1_01,    // PLAYER_ACTION_TOUCH_REACT
    PLAYER_MODELANI_blz_touch1_01,    // PLAYER_ACTION_73
    PLAYER_MODELANI_blz_touch1_01,    // PLAYER_ACTION_74
    PLAYER_MODELANI_blz_fw,           // PLAYER_ACTION_75
    PLAYER_MODELANI_blz_fw,           // PLAYER_ACTION_76
    PLAYER_MODELANI_blz_fw,           // PLAYER_ACTION_77
    PLAYER_MODELANI_com_die_02,       // PLAYER_ACTION_BOSS5FREEZE
    PLAYER_MODELANI_blz_walk6         // PLAYER_ACTION_BOSS6_RUN
};

// clang-format off
const u8 *playerTailAnimForAction[CHARACTER_COUNT] = { 
    [CHARACTER_SONIC] = NULL, 
    [CHARACTER_BLAZE] = tailAnimForActionBlaze
};

const u8 *playerModelIndexForAction[CHARACTER_COUNT] = { 
    [CHARACTER_SONIC] = modelIndexForActionSonic, 
    [CHARACTER_BLAZE] = modelIndexForActionBlaze 
};

const u8 *playerSpriteAnimForAction[CHARACTER_COUNT] = { 
    [CHARACTER_SONIC] = spriteAnimForActionSonic, 
    [CHARACTER_BLAZE] = spriteAnimForActionBlaze 
};

const u8 *playerModelAnimForAction[CHARACTER_COUNT] = { 
    [CHARACTER_SONIC] = modelAnimForActionSonic, 
    [CHARACTER_BLAZE] = modelAnimForActionBlaze 
};
// clang-format on

const struct PlayerPhysicsTable playerPhysicsTable[CHARACTER_COUNT] = {
    // Sonic's physics table
    [CHARACTER_SONIC] = {
        .acceleration            = FLOAT_TO_FX32(0.09375),
        .topSpeed                = FLOAT_TO_FX32(9.0),
        .deceleration            = FLOAT_TO_FX32(0.25),
        .rollingVelocity         = FLOAT_TO_FX32(3.0),
        .rollingAcceleration     = FLOAT_TO_FX32(2.0),
        .rollingTopSpeed         = FLOAT_TO_FX32(8.5),
        .rollingDeceleration     = FLOAT_TO_FX32(0.03125),
        .topSpeed_Boost          = FLOAT_TO_FX32(10.0),
        .acceleration_SuperBoost = FLOAT_TO_FX32(0.1875),
        .topSpeed_SuperBoost     = FLOAT_TO_FX32(12.0),
        .deceleration_SuperBoost = FLOAT_TO_FX32(0.3125),
        .minBoostVelocity        = FLOAT_TO_FX32(6.0),
        .slopeTopSpeedAccel      = FLOAT_TO_FX32(2.0),
        .airTimer                = SECONDS_TO_FRAMES(30.0),
        .hurtInvulnDuration      = SECONDS_TO_FRAMES(3.0),
        .boostActivationTime     = SECONDS_TO_FRAMES(1.6),
        .surfaceStickTimer       = 24,
        .slopeAcceleration       = FLOAT_TO_FX32(0.09375),
        .maxSlopeSpeed           = FLOAT_TO_FX32(15.0),
        .rollSlopeAcceleration   = FLOAT_TO_FX32(0.234375),
        .jumpStrength            = FLOAT_TO_FX32(4.875),
        .gravityStrength         = FLOAT_TO_FX32(0.1640625),
        .terminalVelocity        = FLOAT_TO_FX32(15.0),
        .pushCap                 = FLOAT_TO_FX32(1.75),
    },

    // Blaze's physics table
    [CHARACTER_BLAZE] = {
        .acceleration            = FLOAT_TO_FX32(0.1328125),
        .topSpeed                = FLOAT_TO_FX32(8.5),
        .deceleration            = FLOAT_TO_FX32(0.375),
        .rollingVelocity         = FLOAT_TO_FX32(1.0),
        .rollingAcceleration     = FLOAT_TO_FX32(2.25),
        .rollingTopSpeed         = FLOAT_TO_FX32(7.0),
        .rollingDeceleration     = FLOAT_TO_FX32(0.078125),
        .topSpeed_Boost          = FLOAT_TO_FX32(9.5),
        .acceleration_SuperBoost = FLOAT_TO_FX32(0.3125),
        .topSpeed_SuperBoost     = FLOAT_TO_FX32(10.5),
        .deceleration_SuperBoost = FLOAT_TO_FX32(0.375),
        .minBoostVelocity        = FLOAT_TO_FX32(5.25),
        .slopeTopSpeedAccel      = FLOAT_TO_FX32(2.5),
        .airTimer                = SECONDS_TO_FRAMES(45.0),
        .hurtInvulnDuration      = SECONDS_TO_FRAMES(3.0),
        .boostActivationTime     = SECONDS_TO_FRAMES(2.4),
        .surfaceStickTimer       = 38,
        .slopeAcceleration       = FLOAT_TO_FX32(0.09375),
        .maxSlopeSpeed           = FLOAT_TO_FX32(14.0),
        .rollSlopeAcceleration   = FLOAT_TO_FX32(0.1875),
        .jumpStrength            = FLOAT_TO_FX32(4.875),
        .gravityStrength         = FLOAT_TO_FX32(0.1640625),
        .terminalVelocity        = FLOAT_TO_FX32(15.0),
        .pushCap                 = FLOAT_TO_FX32(1.125),
    },
};