#ifndef RUSH_EXSYSTEM_H
#define RUSH_EXSYSTEM_H

#include <ex/system/exTask.h>

// --------------------
// ENUMS
// --------------------

enum ExSysTaskState_
{
    EXSYSTASK_STATE_0,
    EXSYSTASK_STATE_1,
    EXSYSTASK_STATE_2,
    EXSYSTASK_STATE_3,
    EXSYSTASK_STATE_4,
    EXSYSTASK_STATE_5,
    EXSYSTASK_STATE_6,
    EXSYSTASK_STATE_7,
    EXSYSTASK_STATE_8,
    EXSYSTASK_STATE_9,
    EXSYSTASK_STATE_10,
    EXSYSTASK_STATE_11,
};
typedef u8 ExSysTaskState;

enum ExSysDifficulty_
{
    EXSYS_DIFFICULTY_NONE,
    EXSYS_DIFFICULTY_NORMAL,
    EXSYS_DIFFICULTY_EASY,
};
typedef u8 ExSysDifficulty;

enum ExSysTaskActComAnimIDs
{
    EX_ACTCOM_ANI_0,
    EX_ACTCOM_ANI_1,
    EX_ACTCOM_ANI_2,
    EX_ACTCOM_ANI_SHOCK_EFFECT,
    EX_ACTCOM_ANI_4,
    EX_ACTCOM_ANI_5,
    EX_ACTCOM_ANI_6,
    EX_ACTCOM_ANI_RING,
    EX_ACTCOM_ANI_RING_SPARKLE,
    EX_ACTCOM_ANI_BLAZE_FIRE,
    EX_ACTCOM_ANI_10,
    EX_ACTCOM_ANI_EXPLOSION_BIG,
    EX_ACTCOM_ANI_EXPLOSION_SMALL,
    EX_ACTCOM_ANI_HOMING_LASER,
    EX_ACTCOM_ANI_SUPERSONIC,
    EX_ACTCOM_ANI_BURNINGBLAZE,
    EX_ACTCOM_ANI_LIVES_BACKDROP,
    EX_ACTCOM_ANI_RINGS_BACKDROP,
    EX_ACTCOM_ANI_TIME_TEXT,
    EX_ACTCOM_ANI_LIVES_X,
    EX_ACTCOM_ANI_BOSSGAUGE_EDGE,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_0,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_1,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_2,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_3,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_4,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_5,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_6,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_7,
    EX_ACTCOM_ANI_BOSSGAUGE_BAR_8,
    EX_ACTCOM_ANI_BOSSGAUGE_NAME,
    EX_ACTCOM_ANI_COMMON_DIGIT_0,
    EX_ACTCOM_ANI_COMMON_DIGIT_1,
    EX_ACTCOM_ANI_COMMON_DIGIT_2,
    EX_ACTCOM_ANI_COMMON_DIGIT_3,
    EX_ACTCOM_ANI_COMMON_DIGIT_4,
    EX_ACTCOM_ANI_COMMON_DIGIT_5,
    EX_ACTCOM_ANI_COMMON_DIGIT_6,
    EX_ACTCOM_ANI_COMMON_DIGIT_7,
    EX_ACTCOM_ANI_COMMON_DIGIT_8,
    EX_ACTCOM_ANI_COMMON_DIGIT_9,
    EX_ACTCOM_ANI_COMMA_1,
    EX_ACTCOM_ANI_COMMA_2,
    EX_ACTCOM_ANI_ALERT_DIGIT_0,
    EX_ACTCOM_ANI_ALERT_DIGIT_1,
    EX_ACTCOM_ANI_ALERT_DIGIT_2,
    EX_ACTCOM_ANI_ALERT_DIGIT_3,
    EX_ACTCOM_ANI_ALERT_DIGIT_4,
    EX_ACTCOM_ANI_ALERT_DIGIT_5,
    EX_ACTCOM_ANI_ALERT_DIGIT_6,
    EX_ACTCOM_ANI_ALERT_DIGIT_7,
    EX_ACTCOM_ANI_ALERT_DIGIT_8,
    EX_ACTCOM_ANI_ALERT_DIGIT_9,
    EX_ACTCOM_ANI_ALERT_COMMA_1,
    EX_ACTCOM_ANI_ALERT_COMMA_2,
    EX_ACTCOM_ANI_LIFE_DIGIT_0,
    EX_ACTCOM_ANI_LIFE_DIGIT_1,
    EX_ACTCOM_ANI_LIFE_DIGIT_2,
    EX_ACTCOM_ANI_LIFE_DIGIT_3,
    EX_ACTCOM_ANI_LIFE_DIGIT_4,
    EX_ACTCOM_ANI_LIFE_DIGIT_5,
    EX_ACTCOM_ANI_LIFE_DIGIT_6,
    EX_ACTCOM_ANI_LIFE_DIGIT_7,
    EX_ACTCOM_ANI_LIFE_DIGIT_8,
    EX_ACTCOM_ANI_LIFE_DIGIT_9,
    EX_ACTCOM_ANI_TITLECARD_BACKDROP,
    EX_ACTCOM_ANI_TITLECARD_ICON,
    EX_ACTCOM_ANI_TITLECARD_ACT_BANNER,
    EX_ACTCOM_ANI_TITLECARD_LETTER_E,
    EX_ACTCOM_ANI_TITLECARD_LETTER_X,
    EX_ACTCOM_ANI_TITLECARD_LETTER_T,
    EX_ACTCOM_ANI_TITLECARD_LETTER_R,
    EX_ACTCOM_ANI_TITLECARD_LETTER_A,
    EX_ACTCOM_ANI_TITLECARD_GO_TEXT,
    EX_ACTCOM_ANI_TITLECARD_READY_TEXT,
    EX_ACTCOM_ANI_TITLECARD_ZONE_NAME_TEXT_JP,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BACKDROP,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_JPN,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_JPN,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_ENG,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_ENG,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_FRA,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_FRA,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_DEU,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_DEU,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_ITA,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_ITA,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_SONIC_SPA,
    EX_ACTCOM_ANI_TUTORIAL_TEXT_BLAZE_SPA,
    EX_ACTCOM_ANI_PAUSE_TEXT_JPN,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_JPN,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_JPN,
    EX_ACTCOM_ANI_BACK_BUTTON_JPN,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_JPN,
    EX_ACTCOM_ANI_PAUSE_TEXT_ENG,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_ENG,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_ENG,
    EX_ACTCOM_ANI_BACK_BUTTON_ENG,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_ENG,
    EX_ACTCOM_ANI_PAUSE_TEXT_FRA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_FRA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_FRA,
    EX_ACTCOM_ANI_BACK_BUTTON_FRA,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_FRA,
    EX_ACTCOM_ANI_PAUSE_TEXT_DEU,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_DEU,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_DEU,
    EX_ACTCOM_ANI_BACK_BUTTON_DEU,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_DEU,
    EX_ACTCOM_ANI_PAUSE_TEXT_ITA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_ITA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_ITA,
    EX_ACTCOM_ANI_BACK_BUTTON_ITA,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_ITA,
    EX_ACTCOM_ANI_PAUSE_TEXT_SPA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SPA,
    EX_ACTCOM_ANI_CONTINUE_BUTTON_SELECTED_SPA,
    EX_ACTCOM_ANI_BACK_BUTTON_SPA,
    EX_ACTCOM_ANI_BACK_BUTTON_SELECTED_SPA,
};

// --------------------
// STRUCTS
// --------------------

typedef struct ExSysTaskTime_
{
    u16 field_0;
    u16 minutes;
    u16 tenSeconds;
    u16 seconds;
    u16 frameCounter;
    u16 centiseconds;
} ExSysTaskTime;

typedef struct ExSysTaskStatus_
{
    ExSysDifficulty difficulty;
    u8 finishMode;
    u8 timeLimitMode;
    ExSysTaskState state;
    u8 lives;
    u16 rings;
    ExSysTaskTime time;
} ExSysTaskStatus;

typedef struct ExSysTask_
{
    u32 field_0;
    void *archive;
    u32 field_8;
    s16 timer;
    u16 field_10;
} ExSysTask;

// --------------------
// VARIABLES
// --------------------

// --------------------
// FUNCTIONS
// --------------------

NOT_DECOMPILED void exStageTask__Destroy(void);
NOT_DECOMPILED void exSysTask__GetSingleton(void);
NOT_DECOMPILED s32 exSysTask__GetLifeCount(void);
NOT_DECOMPILED void exSysTask__Func_2172A38(void);
NOT_DECOMPILED void exSysTask__InitStatus(void);
NOT_DECOMPILED ExSysTaskStatus *exSysTask__GetStatus(void);
NOT_DECOMPILED BOOL exSysTask__GetFlag_2178650(void);
NOT_DECOMPILED void exSysTask__Main(void);
NOT_DECOMPILED void exSysTask__Func8(void);
NOT_DECOMPILED void exSysTask__Destructor(void);
NOT_DECOMPILED void exSysTask__Main_2172D30(void);
NOT_DECOMPILED void exSysTask__Func_2172D6C(void);
NOT_DECOMPILED void exSysTask__Main_2172D98(void);
NOT_DECOMPILED void exSysTask__Action_Pause(void);
NOT_DECOMPILED void exSysTask__Main_IsPaused(void);
NOT_DECOMPILED void exSysTask__Main_2172EF8(void);
NOT_DECOMPILED void exSysTask__Func_2172F30(void);
NOT_DECOMPILED void exSysTask__Main_2172FA4(void);
NOT_DECOMPILED void exSysTask__Func_2173000(void);
NOT_DECOMPILED void exSysTask__Main_2173074(void);
NOT_DECOMPILED void exSysTask__Func_21730D0(void);
NOT_DECOMPILED void exSysTask__Main_2173158(void);
NOT_DECOMPILED void exSysTask__Main_21731DC(void);
NOT_DECOMPILED void exSysTask__Main_217323C(void);
NOT_DECOMPILED void exSysTask__Main_21732E4(void);
NOT_DECOMPILED void exSysTask__Main_2173338(void);
NOT_DECOMPILED void exSysTask__Create(void);
NOT_DECOMPILED void *exSysTask__LoadExFile(u16 id);
NOT_DECOMPILED void exSysTask__GetSingleton_Unknown1(void);
NOT_DECOMPILED void exSysTask__LoadAssets(void);
NOT_DECOMPILED void exSysTask__SetupDisplay(void);

#endif // RUSH_EXSYSTEM_H
