#ifndef RUSH_NAVTAILS_H
#define RUSH_NAVTAILS_H

#include <global.h>
#include <game/system/task.h>
#include <game/text/fontAnimator.h>
#include <game/text/fontWindow.h>
#include <game/graphics/sprite.h>

// --------------------
// ENUMS
// --------------------

enum NavTailsMsgSequences
{
    NAVTAILS_MSGSEQ_NONE,
    NAVTAILS_MSGSEQ_WHAT_IS_IT_SONIC,
    NAVTAILS_MSGSEQ_PLEASE_WAIT,
    NAVTAILS_MSGSEQ_ARE_YOU_GOING_TO_QUIT,
    NAVTAILS_MSGSEQ_OKAY_SEE_YOU_LATER,
    NAVTAILS_MSGSEQ_WHERE_ARE_YOU_GOING,
    NAVTAILS_MSGSEQ_GOOD_LUCK_SONIC,
    NAVTAILS_MSGSEQ_GOOD_LUCK_BLAZE,
    NAVTAILS_MSGSEQ_SELECT_AN_ISLAND_TO_GO_TO,
    NAVTAILS_MSGSEQ_THATS_SOUTHERN_ISLAND,
    NAVTAILS_MSGSEQ_THATS_PLANT_KINGDOM,
    NAVTAILS_MSGSEQ_THATS_MACHINE_LABYRINTH,
    NAVTAILS_MSGSEQ_THATS_CORAL_CAVE,
    NAVTAILS_MSGSEQ_THATS_HAUNTED_SHIP,
    NAVTAILS_MSGSEQ_THATS_BLIZZARD_PEAKS,
    NAVTAILS_MSGSEQ_THATS_SKY_BABYLON,
    NAVTAILS_MSGSEQ_THATS_PIRATES_ISLAND,
    NAVTAILS_MSGSEQ_THATS_PIRATES_ISLAND_NO_MATERIAL_VER,
    NAVTAILS_MSGSEQ_THATS_BIG_SWELL,
    NAVTAILS_MSGSEQ_THATS_DEEP_CORE,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_1,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_2,
    NAVTAILS_MSGSEQ_THATS_DAIKUNS_ISLAND,
    NAVTAILS_MSGSEQ_NOTHING,
    NAVTAILS_MSGSEQ_THATS_KYLOKS_ISLAND,
    NAVTAILS_MSGSEQ_LOOKS_LIKE_NO_ONE_IS_HERE,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_3,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_4,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_5,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_6,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_7,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_8,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_9,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_10,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_11,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_12,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_13,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_14,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_15,
    NAVTAILS_MSGSEQ_THATS_HIDDEN_ISLAND_16,
    NAVTAILS_MSGSEQ_WHATS_OUR_NEXT_DESTINATION,
    NAVTAILS_MSGSEQ_WE_CANT_GO_THERE_IN_THIS_SHIP,
    NAVTAILS_MSGSEQ_SHIP_CANT_GO_ANY_FURTHER,
    NAVTAILS_MSGSEQ_IS_THIS_OKAY,
    NAVTAILS_MSGSEQ_GOOD_LUCK_SONIC_VOYAGE_VER,
    NAVTAILS_MSGSEQ_TUTORIAL_TOUCH_WHEN_READY,
    NAVTAILS_MSGSEQ_TUTORIAL_MAP_OF_THE_WORLD,
    NAVTAILS_MSGSEQ_TUTORIAL_CENTER_IS_SOUTHERN_ISLAND,
    NAVTAILS_MSGSEQ_TUTORIAL_SCROLL_MAP_BY_SLIDING,
    NAVTAILS_MSGSEQ_TUTORIAL_CAN_SCROLL_WITH_DPAD_TOO,
    NAVTAILS_MSGSEQ_TUTORIAL_YOU_GOT_HANG_OF_SCROLLING,
    NAVTAILS_MSGSEQ_TUTORIAL_LETS_DRAW_A_COURSE,
    NAVTAILS_MSGSEQ_TUTORIAL_TOUCH_AND_DRAG_TO_DRAW,
    NAVTAILS_MSGSEQ_TUTORIAL_YOU_CAN_TOUCH_TO_SCROLL_WHILE_DRAWING,
    NAVTAILS_MSGSEQ_TUTORIAL_WHEN_DRAWN_ROUTE_PRESS_TO_END,
    NAVTAILS_MSGSEQ_TUTORIAL_YOU_CAN_DRAW_UNTIL_GAUGE_RUNS_OUT,
    NAVTAILS_MSGSEQ_TUTORIAL_HEAD_FOR_MARKED_ISLAND,
    NAVTAILS_MSGSEQ_TUTORIAL_GOOD_JOB,
    NAVTAILS_MSGSEQ_TUTORIAL_YOU_GOT_HANG_OF_DRAWING,
    NAVTAILS_MSGSEQ_TUTORIAL_YOU_GOT_HANG_OF_IT,
};

// --------------------
// STRUCTS
// --------------------

typedef struct NavTailsAssets_
{
    void *archiveNv;
    void *sprNav;
    void *bgNav;
    void *bgMsgWindow[4];
    void *mpcText;
    void *bgTails;
    u32 tailsSpriteID;
} NavTailsAssets;

typedef struct NavTails_
{
    BOOL useEngineB;
    NavTailsAssets assets;
    struct NavTailsDMA
    {
        u32 tailsBackgroundID;
        u16 buffer[2][HW_LCD_HEIGHT];
        u16 updateID;
        u16 timer;
    } dma;
    void (*stateTalk)(struct NavTails_ *work);
    void (*stateDMA)(struct NavTails_ *work);
    u32 shipType;
    u8 lives;
    s32 windowMode;
    s32 messageWindowID;
    FontWindow *fontWindow;
    BOOL usingFontWindowPtr;
    FontWindow _fontWindow;
    FontAnimator fontAnimator;
    void *fontFileData;
    u16 speakDelay;
    u16 speakDuration;
    AnimatorSprite aniWindowElements[3];
    AnimatorSprite aniPlayerIcon;
    AnimatorSprite aniShipIcon[4];
    AnimatorSprite aniLifeNumbers[2];
    AnimatorSprite aniChart[27];
    AnimatorSprite aniUnknown[5];
} NavTails;

// --------------------
// FUNCTIONS
// --------------------

void CreateNavTails(BOOL useEngineB, u32 shipType, FontWindow *window);
void DestroyNavTails(void);
BOOL IsNavTailsActive(void);
void NavTailsSpeak(u16 msgSequence, u16 duration);
u16 CheckNavTailsSpeaking(void);
BOOL CheckNavTailsLastDialog(void);

#endif // RUSH_NAVTAILS_H