#ifndef RUSH_SEAMAPCOMMON_H
#define RUSH_SEAMAPCOMMON_H

#include <global.h>
#include <game/input/touchInput.h>

#ifdef __cplusplus
extern "C"
{
#endif

// --------------------
// ENUMS
// --------------------

enum ShipType_
{
    SHIP_JET,
    SHIP_BOAT,
    SHIP_HOVER,
    SHIP_SUBMARINE,

    SHIP_COUNT,

    // rarely-used values for magma hurricane
    SHIP_DRILL = SHIP_COUNT,
    SHIP_COUNT_DRILL,

    SHIP_MENU = SHIP_COUNT, // SeaMap menu
};
typedef u32 ShipType;

enum ShipLevel_
{
    SHIP_LEVEL_0,
    SHIP_LEVEL_1,
    SHIP_LEVEL_2,

    SHIP_LEVEL_MAX = SHIP_LEVEL_2,
};
typedef u32 ShipLevel;

enum SeaMapZoomLevel_
{
    SEAMAP_ZOOM_NEAREST,
    SEAMAP_ZOOM_MIDDLE,
    SEAMAP_ZOOM_FARTHEST,
};
typedef u32 SeaMapZoomLevel;

enum SeaMapChCommonAnimIDs
{
    SEAMAP_CHCOM_ANI_0,
    SEAMAP_CHCOM_ANI_1,
    SEAMAP_CHCOM_ANI_2,
    SEAMAP_CHCOM_ANI_3,
    SEAMAP_CHCOM_ANI_4,
    SEAMAP_CHCOM_ANI_5,
    SEAMAP_CHCOM_ANI_6,
    SEAMAP_CHCOM_ANI_7,
    SEAMAP_CHCOM_ANI_8,
    SEAMAP_CHCOM_ANI_9,
    SEAMAP_CHCOM_ANI_10,
    SEAMAP_CHCOM_ANI_11,
    SEAMAP_CHCOM_ANI_12,
    SEAMAP_CHCOM_ANI_13,
    SEAMAP_CHCOM_ANI_14,
    SEAMAP_CHCOM_ANI_15,
    SEAMAP_CHCOM_ANI_16,
    SEAMAP_CHCOM_ANI_17,
    SEAMAP_CHCOM_ANI_18,
    SEAMAP_CHCOM_ANI_19,
    SEAMAP_CHCOM_ANI_20,
    SEAMAP_CHCOM_ANI_21,
    SEAMAP_CHCOM_ANI_22,
    SEAMAP_CHCOM_ANI_23,
    SEAMAP_CHCOM_ANI_24,
    SEAMAP_CHCOM_ANI_25,
    SEAMAP_CHCOM_ANI_26,
    SEAMAP_CHCOM_ANI_27,
    SEAMAP_CHCOM_ANI_28,
    SEAMAP_CHCOM_ANI_29,
    SEAMAP_CHCOM_ANI_30,
    SEAMAP_CHCOM_ANI_31,
    SEAMAP_CHCOM_ANI_32,
    SEAMAP_CHCOM_ANI_33,
    SEAMAP_CHCOM_ANI_34,
    SEAMAP_CHCOM_ANI_35,
    SEAMAP_CHCOM_ANI_36,
    SEAMAP_CHCOM_ANI_37,
    SEAMAP_CHCOM_ANI_38,
    SEAMAP_CHCOM_ANI_39,
    SEAMAP_CHCOM_ANI_40,
    SEAMAP_CHCOM_ANI_41,
    SEAMAP_CHCOM_ANI_42,
    SEAMAP_CHCOM_ANI_43,
    SEAMAP_CHCOM_ANI_44,
    SEAMAP_CHCOM_ANI_45,
    SEAMAP_CHCOM_ANI_46,
    SEAMAP_CHCOM_ANI_47,
    SEAMAP_CHCOM_ANI_48,
    SEAMAP_CHCOM_ANI_49,
    SEAMAP_CHCOM_ANI_50,
    SEAMAP_CHCOM_ANI_51,
    SEAMAP_CHCOM_ANI_52,
    SEAMAP_CHCOM_ANI_53,
    SEAMAP_CHCOM_ANI_54,
    SEAMAP_CHCOM_ANI_55,
    SEAMAP_CHCOM_ANI_56,
    SEAMAP_CHCOM_ANI_57,
    SEAMAP_CHCOM_ANI_58,
    SEAMAP_CHCOM_ANI_59,
    SEAMAP_CHCOM_ANI_60,
    SEAMAP_CHCOM_ANI_61,
    SEAMAP_CHCOM_ANI_62,
    SEAMAP_CHCOM_ANI_63,
    SEAMAP_CHCOM_ANI_64,
    SEAMAP_CHCOM_ANI_65,
    SEAMAP_CHCOM_ANI_66,
    SEAMAP_CHCOM_ANI_67,
    SEAMAP_CHCOM_ANI_68,
    SEAMAP_CHCOM_ANI_69,
    SEAMAP_CHCOM_ANI_70,
    SEAMAP_CHCOM_ANI_71,
    SEAMAP_CHCOM_ANI_72,
    SEAMAP_CHCOM_ANI_73,
    SEAMAP_CHCOM_ANI_74,
    SEAMAP_CHCOM_ANI_75,
    SEAMAP_CHCOM_ANI_76,
    SEAMAP_CHCOM_ANI_77,
    SEAMAP_CHCOM_ANI_78,
    SEAMAP_CHCOM_ANI_79,
    SEAMAP_CHCOM_ANI_80,
    SEAMAP_CHCOM_ANI_81,
    SEAMAP_CHCOM_ANI_82,
    SEAMAP_CHCOM_ANI_83,
    SEAMAP_CHCOM_ANI_84,
    SEAMAP_CHCOM_ANI_85,
    SEAMAP_CHCOM_ANI_86,
    SEAMAP_CHCOM_ANI_87,
    SEAMAP_CHCOM_ANI_88,
    SEAMAP_CHCOM_ANI_89,
    SEAMAP_CHCOM_ANI_90,
    SEAMAP_CHCOM_ANI_91,
    SEAMAP_CHCOM_ANI_92,
    SEAMAP_CHCOM_ANI_93,
    SEAMAP_CHCOM_ANI_94,
    SEAMAP_CHCOM_ANI_95,
    SEAMAP_CHCOM_ANI_96,
    SEAMAP_CHCOM_ANI_97,
    SEAMAP_CHCOM_ANI_98,
    SEAMAP_CHCOM_ANI_99,
    SEAMAP_CHCOM_ANI_100,
    SEAMAP_CHCOM_ANI_101,
    SEAMAP_CHCOM_ANI_102,
    SEAMAP_CHCOM_ANI_103,
    SEAMAP_CHCOM_ANI_104,
    SEAMAP_CHCOM_ANI_105,
    SEAMAP_CHCOM_ANI_106,
    SEAMAP_CHCOM_ANI_107,
    SEAMAP_CHCOM_ANI_108,
    SEAMAP_CHCOM_ANI_109,
    SEAMAP_CHCOM_ANI_110,
    SEAMAP_CHCOM_ANI_111,
    SEAMAP_CHCOM_ANI_112,
    SEAMAP_CHCOM_ANI_113,
    SEAMAP_CHCOM_ANI_114,
    SEAMAP_CHCOM_ANI_115,
    SEAMAP_CHCOM_ANI_116,
    SEAMAP_CHCOM_ANI_117,
    SEAMAP_CHCOM_ANI_118,
    SEAMAP_CHCOM_ANI_119,
    SEAMAP_CHCOM_ANI_120,
    SEAMAP_CHCOM_ANI_121,
    SEAMAP_CHCOM_ANI_122,
    SEAMAP_CHCOM_ANI_123,
    SEAMAP_CHCOM_ANI_124,
    SEAMAP_CHCOM_ANI_125,
    SEAMAP_CHCOM_ANI_126,
    SEAMAP_CHCOM_ANI_127,
    SEAMAP_CHCOM_ANI_128,
    SEAMAP_CHCOM_ANI_129,
    SEAMAP_CHCOM_ANI_130,
    SEAMAP_CHCOM_ANI_131,
    SEAMAP_CHCOM_ANI_132,
    SEAMAP_CHCOM_ANI_133,
    SEAMAP_CHCOM_ANI_134,
    SEAMAP_CHCOM_ANI_135,
    SEAMAP_CHCOM_ANI_136,
    SEAMAP_CHCOM_ANI_137,
    SEAMAP_CHCOM_ANI_138,
    SEAMAP_CHCOM_ANI_139,
    SEAMAP_CHCOM_ANI_140,
    SEAMAP_CHCOM_ANI_141,
    SEAMAP_CHCOM_ANI_142,
    SEAMAP_CHCOM_ANI_143,
    SEAMAP_CHCOM_ANI_144,
    SEAMAP_CHCOM_ANI_145,
    SEAMAP_CHCOM_ANI_146,
    SEAMAP_CHCOM_ANI_147,
};

// --------------------
// STRUCTS
// --------------------

typedef struct SeaMapManagerNode_
{
    NNSFndLink link;
    TouchPos position;
    fx32 distance;
} SeaMapManagerNode;

typedef struct SeaMapManagerNodeGroup_
{
    NNSFndLink link;
    SeaMapManagerNode entryList[64];
    u16 entryCount;
} SeaMapManagerNodeGroup;

typedef struct SeaMapManagerNodeList_
{
    NNSFndList nodes;
    NNSFndList groups;
} SeaMapManagerNodeList;

#ifdef __cplusplus
}
#endif

#endif // RUSH_SEAMAPCOMMON_H