#ifndef RUSH2_STAGE_ASSETS_COMMON_H
#define RUSH2_STAGE_ASSETS_COMMON_H

// --------------------
// ENUMS
// --------------------

enum FileList_ArchiveACT_COM
{
    ARC_ACT_COM_FILE_AC_FIX_BAC,
    ARC_ACT_COM_FILE_AC_FIX_CONT_BAC,
    ARC_ACT_COM_FILE_AC_FIX_MSN_BAC,
    ARC_ACT_COM_FILE_AC_PAUSE_BAC,
    ARC_ACT_COM_FILE_AC_ITM_RING_BAC,
    ARC_ACT_COM_FILE_AC_ITM_BOX_BAC,
    ARC_ACT_COM_FILE_AC_FIX_KEY_LITTLE_BAC,
    ARC_ACT_COM_FILE_AC_EFF_TRICK_BAC,
    ARC_ACT_COM_FILE_AC_EFF_KEMURI_SPIN_BAC,
    ARC_ACT_COM_FILE_AC_EFF_BOOST_BAC,
    ARC_ACT_COM_FILE_AC_EFF_B_JET_BAC,
    ARC_ACT_COM_FILE_AC_EFF_KEMURI_BRAKE_BAC,
    ARC_ACT_COM_FILE_AC_EFF_ZAKO_BOMB_BAC,
    ARC_ACT_COM_FILE_AC_EFF_FOUND_BAC,
    ARC_ACT_COM_FILE_EFF_BARRIER_NSBMD,
    ARC_ACT_COM_FILE_EFF_MAGNET_NSBMD,
    ARC_ACT_COM_FILE_AC_EFF_GRAIND_BAC,
    ARC_ACT_COM_FILE_AC_EFF_YUKIKEMURI_BAC,
    ARC_ACT_COM_FILE_AC_EFF_VITALITY_BAC,
    ARC_ACT_COM_FILE_AC_EFF_BOMB_WATER_BAC,
    ARC_ACT_COM_FILE_AC_EFF_BATTLE_BAC,
    ARC_ACT_COM_FILE_EFFE_STARTDASH_NSBMD,
    ARC_ACT_COM_FILE_EFFE_STARTDASH_NSBCA,
    ARC_ACT_COM_FILE_EFFE_STARTDASH_NSBMA,
    ARC_ACT_COM_FILE_EFFE_STARTDASH_NSBVA,
    ARC_ACT_COM_FILE_GMK_GOAL_CHEST_NSBMD,
    ARC_ACT_COM_FILE_GMK_GOAL_CHEST_NSBCA,
    ARC_ACT_COM_FILE_AC_EFF_GOAL_JEWEL_BAC,
    ARC_ACT_COM_FILE_GMK_CHEST_EFECT_NSBMD,
    ARC_ACT_COM_FILE_GMK_CHEST_EFECT_NSBTA,
    ARC_ACT_COM_FILE_AC_GMK_CHECK_BAC,
    ARC_ACT_COM_FILE_STDM_COM_BAC,
    ARC_ACT_COM_FILE_GMK_START_JUMP_NSBMD,
    ARC_ACT_COM_FILE_GMK_START_JUMP_NSBCA,
    ARC_ACT_COM_FILE_GMK_STDM_JUMP_DF,
    ARC_ACT_COM_FILE_AC_GMK_SWITCH_BAC,
    ARC_ACT_COM_FILE_GMK_SWITCH_DF,
    ARC_ACT_COM_FILE_GMK_SWITCH_TATE_DF,
    ARC_ACT_COM_FILE_CLDM_FIX_BAC,
    ARC_ACT_COM_FILE_CLDM_BASE_BBG,
    ARC_ACT_COM_FILE_CLDM_BSD
};

enum FileList_ArchiveACT_COM_B
{
    ARC_ACT_COM_B_FILE_AC_FIX_BAC,
    ARC_ACT_COM_B_FILE_AC_FIX_BOSS_BAC,
    ARC_ACT_COM_B_FILE_AC_PAUSE_BAC,
    ARC_ACT_COM_B_FILE_AC_ITM_RING3D_BAC,
    ARC_ACT_COM_B_FILE_AC_EFF_TRICK_BAC,
    ARC_ACT_COM_B_FILE_AC_EFF_KEMURI_SPIN_3D_BAC,
    ARC_ACT_COM_B_FILE_AC_EFF_KEMURI_BRAKE3D_BAC,
    ARC_ACT_COM_B_FILE_AC_EFF_B_JET3D_BAC,
    ARC_ACT_COM_B_FILE_STDM_COM_BAC,
    ARC_ACT_COM_B_FILE_AC_EFF_GOAL_JEWEL_BAC,
    ARC_ACT_COM_B_FILE_CLDM_FIX_BAC,
    ARC_ACT_COM_B_FILE_CLDM_BASE_BBG,
    ARC_ACT_COM_B_FILE_CLDM_BSD
};

#endif // RUSH2_STAGE_ASSETS_COMMON_H