#pragma once

// TODO: decompile contest rom, this is just rush2 rom for now

.public _secure
.public SVC_Sqrt
.public SVC_DivRem
.public SVC_UncompressLZ16FromDevice
.public SVC_IsMmemExpanded
.public SVC_UncompressRL8
.public SVC_UncompressRL16FromDevice
.public SVC_CpuSetFast
.public SVC_UnpackBits
.public SVC_UncompressLZ8
.public SVC_CpuSet
.public SVC_Div
.public SVC_SoftReset
.public SVC_Halt
.public SVC_GetCRC16
.public SVC_WaitByLoop
.public SVC_20006AC
.public SVC_UncompressHuffmanFromDevice
.public SVC_WaitIntr