#ifndef RUSH_SAILINITEVENT_H
#define RUSH_SAILINITEVENT_H

#include <global.h>

#ifdef __cplusplus
extern "C"
{
#endif

// --------------------
// MISSIONS
// --------------------

enum SailMission
{
    SAILMISSION_TRAINING_JET_INTRO,
    SAILMISSION_TRAINING_JET,
    SAILMISSION_TRAINING_BOAT,
    SAILMISSION_TRAINING_HOVER,
    SAILMISSION_TRAINING_SUBMARINE,
    SAILMISSION_MISSION_JET,
    SAILMISSION_MISSION_BOAT,
    SAILMISSION_MISSION_HOVER,
    SAILMISSION_MISSION_SUBMARINE,
    SAILMISSION_VIKINGCUP_JET_ACT1,
    SAILMISSION_VIKINGCUP_JET_ACT2,
    SAILMISSION_VIKINGCUP_BOAT_ACT1,
    SAILMISSION_VIKINGCUP_BOAT_ACT2,
    SAILMISSION_VIKINGCUP_HOVER_ACT1,
    SAILMISSION_VIKINGCUP_HOVER_ACT2,
    SAILMISSION_VIKINGCUP_SUBMARINE_ACT1,
    SAILMISSION_VIKINGCUP_SUBMARINE_ACT2,

    SAILMISSION_COUNT,
};

// --------------------
// FUNCTIONS
// --------------------

void ResetSailState(void);
void InitSailEvent(s32 id);
void GetSailUnknownValue(s32 *value, s32 timer);

#ifdef __cplusplus
}
#endif

#endif // !RUSH_SAILINITEVENT_H