#ifndef RUSH2_EFFECT_WATERCOMMON_H
#define RUSH2_EFFECT_WATERCOMMON_H

// --------------------
// ENUMS
// --------------------

enum WaterAnimIDs
{
    WATERBUBBLE_ANI_SPLASH,
    WATERBUBBLE_ANI_BIG_SPLASH,
    WATERBUBBLE_ANI_WATER_WAKE,
    WATERBUBBLE_ANI_WATER_SURFACE,
    WATERBUBBLE_ANI_GUSH_V,
    WATERBUBBLE_ANI_SMALL_SPLASH,
    WATERBUBBLE_ANI_SMALL_WAKE,
    WATERBUBBLE_ANI_GUSH_H,
};

enum WaterBubbleAnimIDs
{
    WATERBUBBLE_ANI_TINY_BUBBLE,
    WATERBUBBLE_ANI_SMALL_BUBBLE,
    WATERBUBBLE_ANI_AIR_BUBBLE,
    WATERBUBBLE_ANI_BUBBLER,
};

enum CountdownBubbleAnimIDs
{
    COUNTDOWNBUBBLE_ANI_BUBBLE_0,
    COUNTDOWNBUBBLE_ANI_BUBBLE_1,
    COUNTDOWNBUBBLE_ANI_BUBBLE_2,
    COUNTDOWNBUBBLE_ANI_BUBBLE_3,
    COUNTDOWNBUBBLE_ANI_BUBBLE_4,
    COUNTDOWNBUBBLE_ANI_BUBBLE_5,
};

#endif // RUSH2_EFFECT_WATERCOMMON_H