#ifndef NITROWIFI_VERSION_H
#define NITROWIFI_VERSION_H

#define SDK_WIFI_VERSION_DATE    20061112
#define SDK_WIFI_VERSION_TIME    346
#define SDK_WIFI_VERSION_MAJOR   1
#define SDK_WIFI_VERSION_MINOR   3
#define SDK_WIFI_VERSION_RELSTEP 30000
#define SDK_WIFI_VERSION_STRING  "1.3.30000.0611120346"

#define SDK_WIFI_BUILDINFO_CW_CC 127
#define SDK_WIFI_BUILDINFO_CW_LD 85

#endif // NITROWIFI_VERSION_H
