#ifndef RUSH2_SND_SYS_H
#define RUSH2_SND_SYS_H

// Sound Archive: Sequences
enum SND_SYS_SEQ
{
	SND_SYS_SEQ_SEQ_J_ITEM,
	SND_SYS_SEQ_SEQ_J_DECORATION,
	SND_SYS_SEQ_SEQ_VILLAGE1_1,
	SND_SYS_SEQ_SEQ_VILLAGE1_2,
	SND_SYS_SEQ_SEQ_VILLAGE2_1,
	SND_SYS_SEQ_SEQ_VILLAGE2_2,
	SND_SYS_SEQ_SEQ_VILLAGE3,
	SND_SYS_SEQ_SEQ_CHART,
	SND_SYS_SEQ_SEQ_ACT_CLEAR,
	SND_SYS_SEQ_SEQ_ACT_CLEAR_T,
	SND_SYS_SEQ_SEQ_BOSS_CLEAR,
	SND_SYS_SEQ_SEQ_BOSS_CLEAR_S,
	SND_SYS_SEQ_SEQ_FINAL_CLEAR,
	SND_SYS_SEQ_SEQ_EXTRA_CLEAR,
	SND_SYS_SEQ_SEQ_NEW_RECORD,
	SND_SYS_SEQ_SEQ_NEW_RECORD_B,
	SND_SYS_SEQ_SEQ_CONVER_NOR,
	SND_SYS_SEQ_SEQ_CONVER_TEN,
	SND_SYS_SEQ_SEQ_CONVER_PIR,
	SND_SYS_SEQ_SEQ_CONVER_FIN,
	SND_SYS_SEQ_SEQ_CONVER_ANX,
	SND_SYS_SEQ_SEQ_CONVER_UND,
	SND_SYS_SEQ_SEQ_OPENING,
	SND_SYS_SEQ_SEQ_DEPARTURE,
	SND_SYS_SEQ_SEQ_STAGE1_3,
	SND_SYS_SEQ_SEQ_BLAZE,
	SND_SYS_SEQ_SEQ_BF_FINAL,
	SND_SYS_SEQ_SEQ_FINALEND,
	SND_SYS_SEQ_SEQ_EGGMAN,
	SND_SYS_SEQ_SEQ_POWER,
	SND_SYS_SEQ_SEQ_TRANSFORM,
	SND_SYS_SEQ_SEQ_LAST_BAD,
	SND_SYS_SEQ_SEQ_LAST_GOOD,
	SND_SYS_SEQ_SEQ_EXTRAEND,
	SND_SYS_SEQ_SEQ_STAFF,
	SND_SYS_SEQ_SEQ_ISLAND,
	SND_SYS_SEQ_SEQ_AF_STAFF,
	SND_SYS_SEQ_SEQ_MYSTERY,
	SND_SYS_SEQ_SEQ_EMERALD,
	SND_SYS_SEQ_SEQ_DOCK,
	SND_SYS_SEQ_SEQ_POWERUP,
	SND_SYS_SEQ_SEQ_DL_SELECT,
	SND_SYS_SEQ_SEQ_DL_RESULT,
};

// Sound Archive: Sequence Archives
enum SND_SYS_SEQ_ARCHIVES
{
	SND_SYS_SEQARC_ARC_TITLE,
	SND_SYS_SEQARC_ARC_VILLAGE,
	SND_SYS_SEQARC_ARC_CHART,
	SND_SYS_SEQARC_ARC_CLEAR,
	SND_SYS_SEQARC_ARC_CLEAR_B,
	SND_SYS_SEQARC_ARC_CLEAR_F,
	SND_SYS_SEQARC_ARC_CLEAR_E,
	SND_SYS_SEQARC_ARC_TA_CLEAR,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B,
	SND_SYS_SEQARC_ARC_CONV_NOR,
	SND_SYS_SEQARC_ARC_CONV_TEN,
	SND_SYS_SEQARC_ARC_CONV_PIR,
	SND_SYS_SEQARC_ARC_CONV_FIN,
	SND_SYS_SEQARC_ARC_CONV_ANX,
	SND_SYS_SEQARC_ARC_CONV_UND,
	SND_SYS_SEQARC_ARC_OPENING,
	SND_SYS_SEQARC_ARC_PROLOGUE,
	SND_SYS_SEQARC_ARC_JETSKI,
	SND_SYS_SEQARC_ARC_SAILING,
	SND_SYS_SEQARC_ARC_HOVER,
	SND_SYS_SEQARC_ARC_SUBMARINE,
	SND_SYS_SEQARC_ARC_DRILL,
	SND_SYS_SEQARC_ARC_STAGE_13,
	SND_SYS_SEQARC_ARC_BLAZE,
	SND_SYS_SEQARC_ARC_BF_FINAL,
	SND_SYS_SEQARC_ARC_FINAL,
	SND_SYS_SEQARC_ARC_EGGMAN,
	SND_SYS_SEQARC_ARC_POWER,
	SND_SYS_SEQARC_ARC_TRANSFORM,
	SND_SYS_SEQARC_ARC_LASTSHOT,
	SND_SYS_SEQARC_ARC_EXTRAEND,
	SND_SYS_SEQARC_ARC_STAFF,
	SND_SYS_SEQARC_ARC_ISLAND,
	SND_SYS_SEQARC_ARC_Z7_DOOR,
	SND_SYS_SEQARC_ARC_AF_STAFF,
	SND_SYS_SEQARC_ARC_MYSTERY,
	SND_SYS_SEQARC_ARC_EMERALD,
	SND_SYS_SEQARC_ARC_DL_PLAY,
};

// Sound Archive: Sequence Archive Entries
// Sound Archive: Sequence Archive => "ARC_TITLE"
enum SND_SYS_SEQARC_ARC_TITLE
{
	SND_SYS_SEQARC_ARC_TITLE_SEQ_SE_T_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_VILLAGE"
enum SND_SYS_SEQARC_ARC_VILLAGE
{
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_PAUSE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_V_DECIDE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_V_CANCELL,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_CURSOL,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_V_POPUP,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_D_DECISION,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_MISTAKE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_V_CHANGE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_ROOT,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_INITIALIZE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_WAVE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_MOVE,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_LOADING,
	SND_SYS_SEQARC_ARC_VILLAGE_SEQ_SE_CORRES_FAIL,
};

// Sound Archive: Sequence Archive => "ARC_CHART"
enum SND_SYS_SEQARC_ARC_CHART
{
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_PAUSE,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_V_DECIDE,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_V_CANCELL,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_CURSOL,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_V_POPUP,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_D_DECISION,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_MISTAKE,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_BUTTON,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_DS,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_CHANGE,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_ROOT,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_INIT,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_LOADING,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_C_FAIL,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_ZOOMIN,
	SND_SYS_SEQARC_ARC_CHART_SEQ_SE_ZOOMOUT,
};

// Sound Archive: Sequence Archive => "ARC_CLEAR"
enum SND_SYS_SEQARC_ARC_CLEAR
{
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_SCORE_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_SUM_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_RANKING,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_STONE,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_KIRAKIRA,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_S_ACT_YES,
	SND_SYS_SEQARC_ARC_CLEAR_SEQ_SE_B_ACT_DOUDA,
};

// Sound Archive: Sequence Archive => "ARC_CLEAR_B"
enum SND_SYS_SEQARC_ARC_CLEAR_B
{
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_SCORE_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_SUM_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_RANKING,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_STONE,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_KIRAKIRA,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_BOSS_HEYGUYS,
	SND_SYS_SEQARC_ARC_CLEAR_B_SEQ_SE_BOSS_WATASHI,
};

// Sound Archive: Sequence Archive => "ARC_CLEAR_F"
enum SND_SYS_SEQARC_ARC_CLEAR_F
{
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_SCORE_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_SUM_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_RANKING,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_STONE,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_KIRAKIRA,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_S_OSHIMAI,
	SND_SYS_SEQARC_ARC_CLEAR_F_SEQ_SE_B_TEKINIMAWASU,
};

// Sound Archive: Sequence Archive => "ARC_CLEAR_E"
enum SND_SYS_SEQARC_ARC_CLEAR_E
{
	SND_SYS_SEQARC_ARC_CLEAR_E_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_E_SEQ_SE_SCORE_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_E_SEQ_SE_SUM_INDICATION,
	SND_SYS_SEQARC_ARC_CLEAR_E_SEQ_SE_RANKING,
	SND_SYS_SEQARC_ARC_CLEAR_E_SEQ_SE_STONE,
};

// Sound Archive: Sequence Archive => "ARC_TA_CLEAR"
enum SND_SYS_SEQARC_ARC_TA_CLEAR
{
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_RANKING_TA,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_DRUM_ROLL,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_TN_CURSOL,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_TN_DECIDE,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_WIFI,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_S_ACT_YES_TA,
	SND_SYS_SEQARC_ARC_TA_CLEAR_SEQ_SE_B_ACT_DOUDA_TA,
};

// Sound Archive: Sequence Archive => "ARC_TA_CLEAR_B"
enum SND_SYS_SEQARC_ARC_TA_CLEAR_B
{
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_FLAME_INDICATION,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_RANKING_TA,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_DRUM_ROLL,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_TB_CURSOL,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_TB_DECIDE,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_WIFI,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_BOSS_HEYGUYS_TA,
	SND_SYS_SEQARC_ARC_TA_CLEAR_B_SEQ_SE_BOSS_WATASHI_TA,
};

// Sound Archive: Sequence Archive => "ARC_CONV_NOR"
enum SND_SYS_SEQARC_ARC_CONV_NOR
{
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_CN_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_CN_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_CN_CUTIN,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_CN_DESTROY,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_FLAME,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_SWITCH,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_GRASS,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_KNOCK,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_DOOR_OPEN,
	SND_SYS_SEQARC_ARC_CONV_NOR_SEQ_SE_NEXT,
};

// Sound Archive: Sequence Archive => "ARC_CONV_TEN"
enum SND_SYS_SEQARC_ARC_CONV_TEN
{
	SND_SYS_SEQARC_ARC_CONV_TEN_SEQ_SE_CT_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_TEN_SEQ_SE_CT_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_TEN_SEQ_SE_CT_CUTIN,
	SND_SYS_SEQARC_ARC_CONV_TEN_SEQ_SE_CT_DESTROY,
	SND_SYS_SEQARC_ARC_CONV_TEN_SEQ_SE_CT_EARTHQUAKE,
};

// Sound Archive: Sequence Archive => "ARC_CONV_PIR"
enum SND_SYS_SEQARC_ARC_CONV_PIR
{
	SND_SYS_SEQARC_ARC_CONV_PIR_SEQ_SE_CP_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_PIR_SEQ_SE_CP_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_PIR_SEQ_SE_CP_DESTROY,
	SND_SYS_SEQARC_ARC_CONV_PIR_SEQ_SE_CP_EARTHQUAKE,
	SND_SYS_SEQARC_ARC_CONV_PIR_SEQ_SE_CP_BIKE,
};

// Sound Archive: Sequence Archive => "ARC_CONV_FIN"
enum SND_SYS_SEQARC_ARC_CONV_FIN
{
	SND_SYS_SEQARC_ARC_CONV_FIN_SEQ_SE_CF_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_FIN_SEQ_SE_CF_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_FIN_SEQ_SE_CF_BIKE,
	SND_SYS_SEQARC_ARC_CONV_FIN_SEQ_SE_CF_CANCELL,
	SND_SYS_SEQARC_ARC_CONV_FIN_SEQ_SE_CF_CURSOL,
};

// Sound Archive: Sequence Archive => "ARC_CONV_ANX"
enum SND_SYS_SEQARC_ARC_CONV_ANX
{
	SND_SYS_SEQARC_ARC_CONV_ANX_SEQ_SE_CA_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_ANX_SEQ_SE_CA_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_ANX_SEQ_SE_WIND_OPEN,
};

// Sound Archive: Sequence Archive => "ARC_CONV_UND"
enum SND_SYS_SEQARC_ARC_CONV_UND
{
	SND_SYS_SEQARC_ARC_CONV_UND_SEQ_SE_CU_DECIDE,
	SND_SYS_SEQARC_ARC_CONV_UND_SEQ_SE_CU_BUTTON,
	SND_SYS_SEQARC_ARC_CONV_UND_SEQ_SE_CU_EARTHQUAKE,
	SND_SYS_SEQARC_ARC_CONV_UND_SEQ_SE_SLAP,
};

// Sound Archive: Sequence Archive => "ARC_OPENING"
enum SND_SYS_SEQARC_ARC_OPENING
{
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_STORM_MAIN,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_STORM_NEAR,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_THUNDER,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_PLANE,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_ALARM,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_INAZUMA,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_BROKEN,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_FALL,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_SPARK,
	SND_SYS_SEQARC_ARC_OPENING_SEQ_SE_OP_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_PROLOGUE"
enum SND_SYS_SEQARC_ARC_PROLOGUE
{
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_P_WAVE,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_P_WAVE2,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_FOOT_SAND1,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_FOOT_SAND2,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_SEAGULL1,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_SEAGULL2,
	SND_SYS_SEQARC_ARC_PROLOGUE_SEQ_SE_P_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_JETSKI"
enum SND_SYS_SEQARC_ARC_JETSKI
{
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_JET_ENGINE1,
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_JET_ENGINE2,
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_JET_START,
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_JET_PASS,
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_J_SEAGULLS,
	SND_SYS_SEQARC_ARC_JETSKI_SEQ_SE_J_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_SAILING"
enum SND_SYS_SEQARC_ARC_SAILING
{
	SND_SYS_SEQARC_ARC_SAILING_SEQ_SE_SAIL_START,
	SND_SYS_SEQARC_ARC_SAILING_SEQ_SE_SAIL_PASS,
	SND_SYS_SEQARC_ARC_SAILING_SEQ_SE_S_SEAGULLS,
	SND_SYS_SEQARC_ARC_SAILING_SEQ_SE_S_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_HOVER"
enum SND_SYS_SEQARC_ARC_HOVER
{
	SND_SYS_SEQARC_ARC_HOVER_SEQ_SE_HOVER_START,
	SND_SYS_SEQARC_ARC_HOVER_SEQ_SE_HOVER_PASS,
	SND_SYS_SEQARC_ARC_HOVER_SEQ_SE_H_SEAGULLS,
	SND_SYS_SEQARC_ARC_HOVER_SEQ_SE_H_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_SUBMARINE"
enum SND_SYS_SEQARC_ARC_SUBMARINE
{
	SND_SYS_SEQARC_ARC_SUBMARINE_SEQ_SE_SUB_START,
	SND_SYS_SEQARC_ARC_SUBMARINE_SEQ_SE_SUB_PASS,
	SND_SYS_SEQARC_ARC_SUBMARINE_SEQ_SE_S_SEAGULLS,
	SND_SYS_SEQARC_ARC_SUBMARINE_SEQ_SE_S_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_DRILL"
enum SND_SYS_SEQARC_ARC_DRILL
{
	SND_SYS_SEQARC_ARC_DRILL_SEQ_SE_DRILL_TURN,
	SND_SYS_SEQARC_ARC_DRILL_SEQ_SE_DRILL_START,
	SND_SYS_SEQARC_ARC_DRILL_SEQ_SE_ROCK1,
	SND_SYS_SEQARC_ARC_DRILL_SEQ_SE_ROCK2,
	SND_SYS_SEQARC_ARC_DRILL_SEQ_SE_DR_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_STAGE_13"
enum SND_SYS_SEQARC_ARC_STAGE_13
{
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_1B_WALK,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_1B_ROAR,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_3B_WALK,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_WH_LAUGH,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_FOOTSTEP,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_BRAKE,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_13_BUTTON,
	SND_SYS_SEQARC_ARC_STAGE_13_SEQ_SE_13_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_BLAZE"
enum SND_SYS_SEQARC_ARC_BLAZE
{
	SND_SYS_SEQARC_ARC_BLAZE_SEQ_SE_BL_FIRE,
	SND_SYS_SEQARC_ARC_BLAZE_SEQ_SE_BL_LAND,
	SND_SYS_SEQARC_ARC_BLAZE_SEQ_SE_BL_BUTTON,
	SND_SYS_SEQARC_ARC_BLAZE_SEQ_SE_BL_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_BF_FINAL"
enum SND_SYS_SEQARC_ARC_BF_FINAL
{
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_SPINDASH,
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_HIT,
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_M_FALL,
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_BF_BRAKE,
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_CATCH,
	SND_SYS_SEQARC_ARC_BF_FINAL_SEQ_SE_BF_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_FINAL"
enum SND_SYS_SEQARC_ARC_FINAL
{
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_HIT,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_LAND,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_SLIP,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_SPARK,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_RUN,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_BOSS_EXP,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_L_EXP,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_DECIDE,
	SND_SYS_SEQARC_ARC_FINAL_SEQ_SE_FE_WAVE,
};

// Sound Archive: Sequence Archive => "ARC_EGGMAN"
enum SND_SYS_SEQARC_ARC_EGGMAN
{
	SND_SYS_SEQARC_ARC_EGGMAN_SEQ_SE_DE_EARTH,
	SND_SYS_SEQARC_ARC_EGGMAN_SEQ_SE_DE_SURFACE,
	SND_SYS_SEQARC_ARC_EGGMAN_SEQ_SE_DE_BOSS,
	SND_SYS_SEQARC_ARC_EGGMAN_SEQ_SE_DE_DECIDE,
	SND_SYS_SEQARC_ARC_EGGMAN_SEQ_SE_EGGMAN,
};

// Sound Archive: Sequence Archive => "ARC_POWER"
enum SND_SYS_SEQARC_ARC_POWER
{
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_UG_RUN,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_WAND,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_UG_POWER,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_GIGANTIC,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_UG_DECIDE,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_UG_BUTTON,
	SND_SYS_SEQARC_ARC_POWER_SEQ_SE_UG_EARTHQUAKE,
};

// Sound Archive: Sequence Archive => "ARC_TRANSFORM"
enum SND_SYS_SEQARC_ARC_TRANSFORM
{
	SND_SYS_SEQARC_ARC_TRANSFORM_SEQ_SE_EMERALD,
	SND_SYS_SEQARC_ARC_TRANSFORM_SEQ_SE_EMERALD_SPIN,
	SND_SYS_SEQARC_ARC_TRANSFORM_SEQ_SE_EMERALD_FLASH,
	SND_SYS_SEQARC_ARC_TRANSFORM_SEQ_SE_SUPER,
	SND_SYS_SEQARC_ARC_TRANSFORM_SEQ_SE_TR_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_LASTSHOT"
enum SND_SYS_SEQARC_ARC_LASTSHOT
{
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_QIGONG,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_M_ATTACK,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_GAZE,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_DASH,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_ZOOM,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_B_UPPER,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_S_HIT,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_BF_EXP,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_EXPLOSION,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_LS_BUTTON,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_LS_DECIDE,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_E_AITA,
	SND_SYS_SEQARC_ARC_LASTSHOT_SEQ_SE_ALL_RIGHT,
};

// Sound Archive: Sequence Archive => "ARC_EXTRAEND"
enum SND_SYS_SEQARC_ARC_EXTRAEND
{
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_EE_WAVE,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_HANDSHAKE,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_S_ENGINE,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_M_ENGINE,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_JUMP,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_FLYING,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_EE_BUTTON,
	SND_SYS_SEQARC_ARC_EXTRAEND_SEQ_SE_EE_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_STAFF"
enum SND_SYS_SEQARC_ARC_STAFF
{
	SND_SYS_SEQARC_ARC_STAFF_SEQ_SE_SR_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_ISLAND"
enum SND_SYS_SEQARC_ARC_ISLAND
{
	SND_SYS_SEQARC_ARC_ISLAND_SEQ_SE_SURFACE,
	SND_SYS_SEQARC_ARC_ISLAND_SEQ_SE_I_SEAGULLS,
	SND_SYS_SEQARC_ARC_ISLAND_SEQ_SE_RUMBLE,
	SND_SYS_SEQARC_ARC_ISLAND_SEQ_SE_I_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_Z7_DOOR"
enum SND_SYS_SEQARC_ARC_Z7_DOOR
{
	SND_SYS_SEQARC_ARC_Z7_DOOR_SEQ_SE_VIBRATION,
	SND_SYS_SEQARC_ARC_Z7_DOOR_SEQ_SE_Z7_DOOR,
	SND_SYS_SEQARC_ARC_Z7_DOOR_SEQ_SE_Z7_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_AF_STAFF"
enum SND_SYS_SEQARC_ARC_AF_STAFF
{
	SND_SYS_SEQARC_ARC_AF_STAFF_SEQ_SE_BIKE_OFF,
	SND_SYS_SEQARC_ARC_AF_STAFF_SEQ_SE_EX_DECIDE,
};

// Sound Archive: Sequence Archive => "ARC_MYSTERY"
enum SND_SYS_SEQARC_ARC_MYSTERY
{
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_M_DECIDE,
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_M_CANCELL,
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_DS,
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_MONUMENT,
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_SUCCESS,
	SND_SYS_SEQARC_ARC_MYSTERY_SEQ_SE_P_BUTTON,
};

// Sound Archive: Sequence Archive => "ARC_EMERALD"
enum SND_SYS_SEQARC_ARC_EMERALD
{
	SND_SYS_SEQARC_ARC_EMERALD_SEQ_SE_EMERALD_FLIGHT,
	SND_SYS_SEQARC_ARC_EMERALD_SEQ_SE_EMERALD_FIX,
	SND_SYS_SEQARC_ARC_EMERALD_SEQ_SE_EMERALD_SHINE,
};

// Sound Archive: Sequence Archive => "ARC_DL_PLAY"
enum SND_SYS_SEQARC_ARC_DL_PLAY
{
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_DECIDE,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_CANCELL,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_CURSOL,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_CORRES_FAIL,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_FLAME,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_SCORE,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_SUM,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_D_RANKING,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_S_YES,
	SND_SYS_SEQARC_ARC_DL_PLAY_SEQ_SE_B_DOUDA,
};

// Sound Archive: Intrument Banks
enum SND_SYS_INSTRUMENT_BANKS
{
	SND_SYS_BANK_BANK_TITLE,
	SND_SYS_BANK_BANK_J_ITEM,
	SND_SYS_BANK_BANK_VILLAGE1_1,
	SND_SYS_BANK_BANK_VILLAGE1_2,
	SND_SYS_BANK_BANK_VILLAGE2_1,
	SND_SYS_BANK_BANK_VILLAGE2_2,
	SND_SYS_BANK_BANK_VILLAGE3,
	SND_SYS_BANK_BANK_CHART,
	SND_SYS_BANK_BANK_VILLAGE_SE,
	SND_SYS_BANK_BANK_CHART_SE,
	SND_SYS_BANK_BANK_CLEAR,
	SND_SYS_BANK_BANK_CLEAR_T,
	SND_SYS_BANK_BANK_CLEAR_SE,
	SND_SYS_BANK_BANK_CLEAR_B,
	SND_SYS_BANK_BANK_CLEAR_S,
	SND_SYS_BANK_BANK_CLEAR_B_SE,
	SND_SYS_BANK_BANK_CLEAR_F,
	SND_SYS_BANK_BANK_CLEAR_E,
	SND_SYS_BANK_BANK_TA_CLEAR,
	SND_SYS_BANK_BANK_TA_CLEAR_B,
	SND_SYS_BANK_BANK_RECORD,
	SND_SYS_BANK_BANK_RECORD_B,
	SND_SYS_BANK_BANK_NORMAL,
	SND_SYS_BANK_BANK_TENSION,
	SND_SYS_BANK_BANK_PIRATES,
	SND_SYS_BANK_BANK_FINAL,
	SND_SYS_BANK_BANK_ANXIETY,
	SND_SYS_BANK_BANK_UNDER,
	SND_SYS_BANK_BANK_CONV_NOR,
	SND_SYS_BANK_BANK_CONV_TEN,
	SND_SYS_BANK_BANK_CONV_PIR,
	SND_SYS_BANK_BANK_CONV_FIN,
	SND_SYS_BANK_BANK_CONV_ANX,
	SND_SYS_BANK_BANK_CONV_UND,
	SND_SYS_BANK_BANK_OPENING,
	SND_SYS_BANK_BANK_PROLOGUE,
	SND_SYS_BANK_BANK_DEPARTURE,
	SND_SYS_BANK_BANK_JETSKI,
	SND_SYS_BANK_BANK_SAILING,
	SND_SYS_BANK_BANK_HOVER,
	SND_SYS_BANK_BANK_SUBMARINE,
	SND_SYS_BANK_BANK_DRILL,
	SND_SYS_BANK_BANK_STAGE1_3,
	SND_SYS_BANK_BANK_STAGE13_SE,
	SND_SYS_BANK_BANK_BLAZE,
	SND_SYS_BANK_BANK_BF_FINAL,
	SND_SYS_BANK_BANK_BF_FINAL_SE,
	SND_SYS_BANK_BANK_FINALEND,
	SND_SYS_BANK_BANK_FINAL_SE,
	SND_SYS_BANK_BANK_EGGMAN,
	SND_SYS_BANK_BANK_EGGMAN_SE,
	SND_SYS_BANK_BANK_POWER,
	SND_SYS_BANK_BANK_POWER_SE,
	SND_SYS_BANK_BANK_TRANSFORM,
	SND_SYS_BANK_BANK_EXTRALAST,
	SND_SYS_BANK_BANK_LAST_SE,
	SND_SYS_BANK_BANK_EXTRAEND,
	SND_SYS_BANK_BANK_EXTRAEND_SE,
	SND_SYS_BANK_BANK_STAFF,
	SND_SYS_BANK_BANK_ISLAND,
	SND_SYS_BANK_BANK_Z7_DOOR,
	SND_SYS_BANK_BANK_AF_STAFF,
	SND_SYS_BANK_BANK_AF_STAFF_SE,
	SND_SYS_BANK_BANK_MYSTERY,
	SND_SYS_BANK_BANK_EMERALD,
	SND_SYS_BANK_BANK_EMERALD_SE,
	SND_SYS_BANK_BANK_DL_PLAY_S,
	SND_SYS_BANK_BANK_DL_PLAY_R,
	SND_SYS_BANK_BANK_DOCK,
	SND_SYS_BANK_BANK_POWERUP,
};

// Sound Archive: Wave Archives
enum SND_SYS_WAVE_ARCHIVES
{
	SND_SYS_WAVEARC_WAVE_TITLE,
	SND_SYS_WAVEARC_WAVE_J_ITEM,
	SND_SYS_WAVEARC_WAVE_VILLAGE1_1,
	SND_SYS_WAVEARC_WAVE_VILLAGE1_2,
	SND_SYS_WAVEARC_WAVE_VILLAGE2_1,
	SND_SYS_WAVEARC_WAVE_VILLAGE2_2,
	SND_SYS_WAVEARC_WAVE_VILLAGE3,
	SND_SYS_WAVEARC_WAVE_CHART,
	SND_SYS_WAVEARC_WAVE_VILLAGE_SE,
	SND_SYS_WAVEARC_WAVE_CHART_SE,
	SND_SYS_WAVEARC_WAVE_CLEAR,
	SND_SYS_WAVEARC_WAVE_CLEAR_T,
	SND_SYS_WAVEARC_WAVE_CLEAR_SE,
	SND_SYS_WAVEARC_WAVE_CLEAR_B,
	SND_SYS_WAVEARC_WAVE_CLEAR_S,
	SND_SYS_WAVEARC_WAVE_CLEAR_B_SE,
	SND_SYS_WAVEARC_WAVE_CLEAR_F,
	SND_SYS_WAVEARC_WAVE_CLEAR_E,
	SND_SYS_WAVEARC_WAVE_TA_CLEAR,
	SND_SYS_WAVEARC_WAVE_TA_CLEAR_B,
	SND_SYS_WAVEARC_WAVE_NORMAL,
	SND_SYS_WAVEARC_WAVE_TENSION,
	SND_SYS_WAVEARC_WAVE_PIRATES,
	SND_SYS_WAVEARC_WAVE_FINAL,
	SND_SYS_WAVEARC_WAVE_ANXIETY,
	SND_SYS_WAVEARC_WAVE_UNDER,
	SND_SYS_WAVEARC_WAVE_CONV_NOR,
	SND_SYS_WAVEARC_WAVE_CONV_TEN,
	SND_SYS_WAVEARC_WAVE_CONV_PIR,
	SND_SYS_WAVEARC_WAVE_CONV_FIN,
	SND_SYS_WAVEARC_WAVE_CONV_ANX,
	SND_SYS_WAVEARC_WAVE_CONV_UND,
	SND_SYS_WAVEARC_WAVE_OPENING,
	SND_SYS_WAVEARC_WAVE_PROLOGUE,
	SND_SYS_WAVEARC_WAVE_DEPARTURE,
	SND_SYS_WAVEARC_WAVE_JETSKI,
	SND_SYS_WAVEARC_WAVE_SAILING,
	SND_SYS_WAVEARC_WAVE_HOVER,
	SND_SYS_WAVEARC_WAVE_SUBMARINE,
	SND_SYS_WAVEARC_WAVE_DRILL,
	SND_SYS_WAVEARC_WAVE_STAGE1_3,
	SND_SYS_WAVEARC_WAVE_STAGE13_SE,
	SND_SYS_WAVEARC_WAVE_BLAZE,
	SND_SYS_WAVEARC_WAVE_BF_FINAL,
	SND_SYS_WAVEARC_WAVE_FINALEND,
	SND_SYS_WAVEARC_WAVE_FINAL_SE,
	SND_SYS_WAVEARC_WAVE_EGGMAN,
	SND_SYS_WAVEARC_WAVE_POWER,
	SND_SYS_WAVEARC_WAVE_POWER_SE,
	SND_SYS_WAVEARC_WAVE_TRANSFORM,
	SND_SYS_WAVEARC_WAVE_EXTRALAST,
	SND_SYS_WAVEARC_WAVE_LAST_SE,
	SND_SYS_WAVEARC_WAVE_EXTRAEND,
	SND_SYS_WAVEARC_WAVE_EXTRAEND_SE,
	SND_SYS_WAVEARC_WAVE_STAFF,
	SND_SYS_WAVEARC_WAVE_ISLAND,
	SND_SYS_WAVEARC_WAVE_Z7_DOOR,
	SND_SYS_WAVEARC_WAVE_AF_STAFF,
	SND_SYS_WAVEARC_WAVE_AF_STAFF_SE,
	SND_SYS_WAVEARC_WAVE_MYSTERY,
	SND_SYS_WAVEARC_WAVE_EMERALD,
	SND_SYS_WAVEARC_WAVE_EMERALD_SE,
	SND_SYS_WAVEARC_WAVE_DL_PLAY,
	SND_SYS_WAVEARC_WAVE_DOCK,
	SND_SYS_WAVEARC_WAVE_POWERUP,
};

// Sound Archive: Sequence Players
enum SND_SYS_SEQ_PLAYER
{
	SND_SYS_SEQPLAYER_PLAYER_BGM,
	SND_SYS_SEQPLAYER_PLAYER_1,
	SND_SYS_SEQPLAYER_PLAYER_2,
	SND_SYS_SEQPLAYER_PLAYER_3,
};

// Sound Archive: Groups
enum SND_SYS_GROUPS
{
	SND_SYS_GROUP_TITLE,
	SND_SYS_GROUP_VILLAGE1_1,
	SND_SYS_GROUP_VILLAGE1_2,
	SND_SYS_GROUP_VILLAGE2_1,
	SND_SYS_GROUP_VILLAGE2_2,
	SND_SYS_GROUP_VILLAGE3,
	SND_SYS_GROUP_CHART,
	SND_SYS_GROUP_CLEAR,
	SND_SYS_GROUP_CLEAR_B,
	SND_SYS_GROUP_CLEAR_F,
	SND_SYS_GROUP_CLEAR_E,
	SND_SYS_GROUP_TA_CLEAR,
	SND_SYS_GROUP_TA_CLEAR_B,
	SND_SYS_GROUP_CONVER_NOR,
	SND_SYS_GROUP_CONVER_TEN,
	SND_SYS_GROUP_CONVER_PIR,
	SND_SYS_GROUP_CONVER_FIN,
	SND_SYS_GROUP_CONVER_ANX,
	SND_SYS_GROUP_CONVER_UND,
	SND_SYS_GROUP_OPENING,
	SND_SYS_GROUP_PROLOGUE,
	SND_SYS_GROUP_JETSKI,
	SND_SYS_GROUP_SAILING,
	SND_SYS_GROUP_HOVER,
	SND_SYS_GROUP_SUBMARINE,
	SND_SYS_GROUP_DRILL,
	SND_SYS_GROUP_STAGE1_3,
	SND_SYS_GROUP_BLAZE,
	SND_SYS_GROUP_BF_FINAL,
	SND_SYS_GROUP_FINALEND,
	SND_SYS_GROUP_EGGMAN,
	SND_SYS_GROUP_POWER,
	SND_SYS_GROUP_TRANSFORM,
	SND_SYS_GROUP_EXTRALAST,
	SND_SYS_GROUP_EXTRAEND,
	SND_SYS_GROUP_STAFF,
	SND_SYS_GROUP_ISLAND,
	SND_SYS_GROUP_Z7_DOOR,
	SND_SYS_GROUP_AF_STAFF,
	SND_SYS_GROUP_MYSTERY,
	SND_SYS_GROUP_EMERALD,
	SND_SYS_GROUP_DOCK,
	SND_SYS_GROUP_POWERUP,
	SND_SYS_GROUP_DL_PLAY,
};

// Sound Archive: Stream Players
enum SND_SYS_STRM_PLAYER
{
	SND_SYS_STRMPLAYER_PLAYER_STRM,
};

// Sound Archive: Streams
enum SND_SYS_STREAMS
{
	SND_SYS_STRM_TITLEDEMO,
	SND_SYS_STRM_DEMO_TEST,
	SND_SYS_STRM_TITLE,
};

#endif // !RUSH2_SND_SYS_H
